//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexrothData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RexrothEntities : DbContext
    {
        public RexrothEntities()
            : base("name=RexrothEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAssociate> tblAssociate { get; set; }
    
        public virtual int p_SaveChangesEF(string firstN, string lastN, string userN, string email, string display, ObjectParameter pK, ObjectParameter eMessage)
        {
            var firstNParameter = firstN != null ?
                new ObjectParameter("FirstN", firstN) :
                new ObjectParameter("FirstN", typeof(string));
    
            var lastNParameter = lastN != null ?
                new ObjectParameter("LastN", lastN) :
                new ObjectParameter("LastN", typeof(string));
    
            var userNParameter = userN != null ?
                new ObjectParameter("UserN", userN) :
                new ObjectParameter("UserN", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var displayParameter = display != null ?
                new ObjectParameter("Display", display) :
                new ObjectParameter("Display", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_SaveChangesEF", firstNParameter, lastNParameter, userNParameter, emailParameter, displayParameter, pK, eMessage);
        }
    }
}
