//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexrothData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssociate
    {
        public int ASID { get; set; }
        public Nullable<int> PERNR { get; set; }
        public Nullable<int> DPID { get; set; }
        public Nullable<int> OFID { get; set; }
        public Nullable<int> BIDID { get; set; }
        public string AS_Display { get; set; }
        public string AS_First { get; set; }
        public string AS_Phone { get; set; }
        public string AS_Last { get; set; }
        public string AS_User { get; set; }
        public string AS_OutID { get; set; }
        public Nullable<System.DateTime> AS_Sync { get; set; }
        public bool AS_Active { get; set; }
        public bool AS_Reso { get; set; }
        public string AS_Email { get; set; }
        public Nullable<int> AS_Bosch { get; set; }
        public string AS_Domain { get; set; }
        public string AS_Group { get; set; }
        public Nullable<bool> AS_DC { get; set; }
        public Nullable<bool> AS_SuperUser { get; set; }
        public int AS_Unique { get; set; }
        public string AS_Unique_Email { get; set; }
        public string AS_Unique_UseID { get; set; }
        public Nullable<int> VSID { get; set; }
        public Nullable<System.DateTime> AS_Inactivated { get; set; }
        public Nullable<int> MergeKeep { get; set; }
        public Nullable<int> AS_Read { get; set; }
        public string AS_Path { get; set; }
        public Nullable<int> AS_Kronos { get; set; }
        public Nullable<System.DateTime> AS_Created { get; set; }
        public string AS_Shift { get; set; }
        public string AS_Text { get; set; }
        public string AS_WorkScheduleRule { get; set; }
        public string AS_SupervisorEmail { get; set; }
        public Nullable<int> AS_CostCenter { get; set; }
        public string AS_Badge { get; set; }
        public string AS_CellForSMS { get; set; }
        public Nullable<int> AS_CareerBand { get; set; }
        public string AS_OrgUnitAbbr { get; set; }
        public bool AS_BInonFNI { get; set; }
        public bool AS_MachText { get; set; }
        public bool AS_BI_Lock { get; set; }
        public bool AS_CBandLock { get; set; }
        public string AS_HTI_Manager { get; set; }
    }
}
