//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaaPKOldLeakTest
    {
        public Nullable<int> hour { get; set; }
        public Nullable<int> minit { get; set; }
        public Nullable<int> serialnumber { get; set; }
        public Nullable<int> PKLine { get; set; }
        public Nullable<int> cntPass { get; set; }
        public Nullable<int> cntFail { get; set; }
        public string WorkOrder { get; set; }
        public Nullable<int> GridCol { get; set; }
        public Nullable<int> Bucket { get; set; }
        public int id { get; set; }
        public Nullable<int> Bucket2 { get; set; }
    }
}
