//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuilding
    {
        public int BLDID { get; set; }
        public string BLD_Desc { get; set; }
        public string BLD_Long { get; set; }
        public Nullable<System.DateTime> BLD_Deleted { get; set; }
        public System.DateTime BLD_Created { get; set; }
        public Nullable<int> PRID { get; set; }
    }
}
