//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerNumber
    {
        public int CSNID { get; set; }
        public int CUSID { get; set; }
        public string CSN_Desc { get; set; }
        public System.DateTime CSN_Date { get; set; }
        public string CSN_Long { get; set; }
    }
}
