//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDSB_Status
    {
        public int DSTID { get; set; }
        public int MASTID { get; set; }
        public string DST_Desc { get; set; }
        public int DST_Active { get; set; }
        public string DST_SAP { get; set; }
        public int DST_Sort { get; set; }
        public int ARID { get; set; }
        public string DST_Short { get; set; }
        public Nullable<int> DST_Visual { get; set; }
        public string DST_SAP4 { get; set; }
        public Nullable<int> DST_RptSort { get; set; }
        public Nullable<int> DST_QVS { get; set; }
    }
}
