//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFPYTargets
    {
        public int FPYTID { get; set; }
        public System.DateTime FPYT_Created { get; set; }
        public Nullable<System.DateTime> FPYT_Deleted { get; set; }
        public Nullable<int> FPY_ShiftTarget { get; set; }
        public Nullable<int> FPY_TwentyFourTarget { get; set; }
        public Nullable<int> Nu_ShiftTarget { get; set; }
        public Nullable<int> Nu_TwentyFourTarget { get; set; }
        public Nullable<int> VSID { get; set; }
    }
}
