//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFPYResults
    {
        public int FPYRID { get; set; }
        public int ID { get; set; }
        public Nullable<int> TotalTests { get; set; }
        public Nullable<int> FirstPass { get; set; }
        public Nullable<int> Fails { get; set; }
        public Nullable<double> FPY { get; set; }
        public Nullable<double> CycleTime { get; set; }
        public Nullable<double> Nu { get; set; }
        public Nullable<System.DateTime> ResultsDate { get; set; }
        public string Source { get; set; }
        public Nullable<int> VSID { get; set; }
    }
}
