//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFPYBreaks
    {
        public int FPYID { get; set; }
        public System.DateTime FPY_Created { get; set; }
        public Nullable<System.DateTime> FPY_Deleted { get; set; }
        public Nullable<int> FPY_Hour { get; set; }
        public string FPY_Desc { get; set; }
        public string FPY_Shift { get; set; }
        public Nullable<int> FPY_StartMinute { get; set; }
        public Nullable<int> FPY_TotalMinutes { get; set; }
    }
}
