//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIssue
    {
        public int IUID { get; set; }
        public int IDID { get; set; }
        public Nullable<int> IVID { get; set; }
        public Nullable<int> ICID { get; set; }
        public Nullable<int> VSID { get; set; }
        public Nullable<int> DSTID { get; set; }
        public string IU_Order { get; set; }
        public Nullable<System.DateTime> IU_Deleted { get; set; }
        public string IU_Part { get; set; }
        public Nullable<int> IU_Qty { get; set; }
        public string IX_BoxQty { get; set; }
        public string IU_UserID { get; set; }
        public string IU_Badge { get; set; }
        public Nullable<int> WOID { get; set; }
        public Nullable<int> IPID { get; set; }
        public bool IU_TOCreated { get; set; }
        public bool IU_SAP { get; set; }
        public Nullable<int> ITID { get; set; }
        public string IU_BinLocation { get; set; }
        public Nullable<int> VOID { get; set; }
        public Nullable<int> BldgOneCleared { get; set; }
    }
}
