//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitterAuditQuestions
    {
        public int AQID { get; set; }
        public string AQ_Desc { get; set; }
        public bool AQ_Active { get; set; }
        public System.DateTime AQ_Created { get; set; }
        public Nullable<System.DateTime> AQ_Deleted { get; set; }
    }
}
