//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitterAuditError
    {
        public int AEID { get; set; }
        public string AE_Desc { get; set; }
        public bool AE_Active { get; set; }
        public System.DateTime AE_Created { get; set; }
        public Nullable<System.DateTime> AE_Deleted { get; set; }
    }
}
