//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitterAudit
    {
        public int KQID { get; set; }
        public string KQ_Desc { get; set; }
        public bool KQ_Active { get; set; }
        public System.DateTime KQ_Created { get; set; }
        public Nullable<System.DateTime> KQ_Deleted { get; set; }
        public Nullable<int> AQID { get; set; }
        public Nullable<int> KIID { get; set; }
        public Nullable<int> KQ_Answer { get; set; }
        public Nullable<bool> KQ_Corrected { get; set; }
        public Nullable<System.DateTime> KQ_CorrectedDate { get; set; }
        public string KQ_Comment { get; set; }
    }
}
