//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitter
    {
        public int KIID { get; set; }
        public string KI_Badge { get; set; }
        public Nullable<int> ASID { get; set; }
        public int WOID { get; set; }
        public System.DateTime KI_Timestamp { get; set; }
        public string AU_Badge { get; set; }
        public Nullable<int> AU_ASID { get; set; }
        public Nullable<System.DateTime> AU_Timestamp { get; set; }
        public bool KI_Good { get; set; }
        public Nullable<int> AEID { get; set; }
        public string AU_Comment { get; set; }
        public Nullable<int> AU_Count { get; set; }
    }
}
