//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitterStatus
    {
        public int KSID { get; set; }
        public string KS_Desc { get; set; }
        public bool KS_Active { get; set; }
        public System.DateTime KS_Created { get; set; }
        public Nullable<System.DateTime> KS_Deleted { get; set; }
    }
}
