//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeakTestCycleTime
    {
        public int LTCYID { get; set; }
        public System.DateTime LTCY_Created { get; set; }
        public Nullable<System.DateTime> LTCY_Deleted { get; set; }
        public string LTCY_Part { get; set; }
        public Nullable<decimal> LTCY_Time { get; set; }
        public string LTCY_Family { get; set; }
        public string LTCY_Line { get; set; }
        public Nullable<decimal> LTCY_HousingTime { get; set; }
        public Nullable<decimal> LTCY_FlangeTime { get; set; }
        public Nullable<decimal> LTCY_BoltUpTime { get; set; }
    }
}
