//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRPController
    {
        public int MRPID { get; set; }
        public string MRP_Number { get; set; }
        public string MRP_Desc { get; set; }
        public int MRP_Type { get; set; }
        public int MRP_Active { get; set; }
        public Nullable<System.DateTime> MRP_Deleted { get; set; }
        public Nullable<int> MPTID { get; set; }
    }
}
