//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartBOMParent
    {
        public int BPID { get; set; }
        public int PARTID { get; set; }
        public System.DateTime BP_Created { get; set; }
        public System.DateTime BP_Updated { get; set; }
        public Nullable<System.DateTime> BP_MaxValidFromPre { get; set; }
        public Nullable<System.DateTime> BP_MaxValidFrom { get; set; }
    
        public virtual tblPart tblPart { get; set; }
    }
}
