//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartFolderPPT
    {
        public tblPartFolderPPT()
        {
            this.tblPartFolderPPTPics = new HashSet<tblPartFolderPPTPics>();
        }
    
        public int PTPTID { get; set; }
        public int PTFLDID { get; set; }
        public string PTPT_Name { get; set; }
        public System.DateTime PTPT_LastUpdated { get; set; }
        public System.DateTime PTPT_TimeStamp { get; set; }
        public byte[] PTPT_PDFImage { get; set; }
    
        public virtual tblPartFolder tblPartFolder { get; set; }
        public virtual ICollection<tblPartFolderPPTPics> tblPartFolderPPTPics { get; set; }
    }
}
