//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartRineerMotorType
    {
        public int RMTID { get; set; }
        public string RMT_Desc { get; set; }
        public Nullable<System.DateTime> RMT_Deleted { get; set; }
        public string RMT_Path { get; set; }
    }
}
