//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartFolder
    {
        public tblPartFolder()
        {
            this.tblPartFolderPPT = new HashSet<tblPartFolderPPT>();
        }
    
        public int PTFLDID { get; set; }
        public int PARTID { get; set; }
        public string PTFLD_Desc { get; set; }
        public System.DateTime PTFLD_Created { get; set; }
        public Nullable<System.DateTime> PTFLD_Deleted { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual ICollection<tblPartFolderPPT> tblPartFolderPPT { get; set; }
    }
}
