//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartRineerPath
    {
        public int PPZID { get; set; }
        public int PSRID { get; set; }
        public int PPTID { get; set; }
        public int PPKID { get; set; }
        public int PDPID { get; set; }
        public int PSFID { get; set; }
        public int PSBID { get; set; }
        public int PSLID { get; set; }
        public int PSPID { get; set; }
        public string PPZ_Desc { get; set; }
        public Nullable<System.DateTime> PPZ_Deleted { get; set; }
    }
}
