//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        public tblPart()
        {
            this.tblPartBOMParent = new HashSet<tblPartBOMParent>();
            this.tblPartFolder = new HashSet<tblPartFolder>();
            this.tblPartRineerMotor = new HashSet<tblPartRineerMotor>();
            this.tblShippingPart = new HashSet<tblShippingPart>();
            this.tblValueMachineCastingPart = new HashSet<tblValueMachineCastingPart>();
            this.tblValueMachineOrder = new HashSet<tblValueMachineOrder>();
            this.tblValueMachinePart = new HashSet<tblValueMachinePart>();
            this.tblValueMachinePartSetup = new HashSet<tblValueMachinePartSetup>();
        }
    
        public int PARTID { get; set; }
        public int CUSID { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public int PART_Active { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> DateImported { get; set; }
        public Nullable<System.DateTime> PART_Deleted { get; set; }
        public Nullable<int> PSRID { get; set; }
        public Nullable<int> PPTID { get; set; }
        public Nullable<int> PPKID { get; set; }
        public Nullable<int> PDPID { get; set; }
        public Nullable<int> PSFID { get; set; }
        public Nullable<int> PSBID { get; set; }
        public Nullable<int> PSLID { get; set; }
        public Nullable<int> PSPID { get; set; }
        public Nullable<byte> PART_Group { get; set; }
        public string PART_Rev { get; set; }
        public string PART_MM { get; set; }
        public string PKList_Comment { get; set; }
        public string PART_CusNumber { get; set; }
        public Nullable<int> PCLID { get; set; }
        public string PART_EBZnum { get; set; }
        public Nullable<bool> US55_Part { get; set; }
        public Nullable<System.DateTime> Part_RevUpdated { get; set; }
    
        public virtual ICollection<tblPartBOMParent> tblPartBOMParent { get; set; }
        public virtual ICollection<tblPartFolder> tblPartFolder { get; set; }
        public virtual ICollection<tblPartRineerMotor> tblPartRineerMotor { get; set; }
        public virtual ICollection<tblShippingPart> tblShippingPart { get; set; }
        public virtual ICollection<tblValueMachineCastingPart> tblValueMachineCastingPart { get; set; }
        public virtual ICollection<tblValueMachineOrder> tblValueMachineOrder { get; set; }
        public virtual ICollection<tblValueMachinePart> tblValueMachinePart { get; set; }
        public virtual ICollection<tblValueMachinePartSetup> tblValueMachinePartSetup { get; set; }
    }
}
