//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartSpecial
    {
        public int PSPID { get; set; }
        public string PSP_Desc { get; set; }
        public Nullable<System.DateTime> PSP_Deleted { get; set; }
    }
}
