//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartFolderPPTPics
    {
        public int PTPPTID { get; set; }
        public int PTPTID { get; set; }
        public int PTPPT_Slide { get; set; }
        public string PTPPT_PicName { get; set; }
        public Nullable<decimal> PTPPT_Top { get; set; }
        public Nullable<decimal> PTPPT_Left { get; set; }
        public Nullable<decimal> PTPPT_Height { get; set; }
        public Nullable<decimal> PTPPT_Width { get; set; }
        public string PTPPT_AltText { get; set; }
        public string PTPPT_Path { get; set; }
        public System.DateTime PTPPT_TimeStamp { get; set; }
    
        public virtual tblPartFolderPPT tblPartFolderPPT { get; set; }
    }
}
