//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPath
    {
        public int PTID { get; set; }
        public int LNID { get; set; }
        public string PT_Desc { get; set; }
        public Nullable<int> OPID { get; set; }
        public Nullable<int> FTID { get; set; }
        public string PT_ArchiveFolder { get; set; }
    }
}
