//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartBOMComp
    {
        public int BCID { get; set; }
        public string BC_ItemNo { get; set; }
        public string BC_Component { get; set; }
        public string BC_CompDesc { get; set; }
        public System.DateTime BC_Created { get; set; }
        public string BC_Fam { get; set; }
        public string BC_Type { get; set; }
        public string BC_Size { get; set; }
        public string BC_Control { get; set; }
        public string BC_X { get; set; }
        public string BC_Rot { get; set; }
        public string BC_Seal { get; set; }
        public string BC_Shaft { get; set; }
        public string BC_Flan { get; set; }
        public string BC_PB { get; set; }
        public string BC_Thdr { get; set; }
        public string BC_Fam1 { get; set; }
        public string BC_Type1 { get; set; }
        public string BC_Size1 { get; set; }
        public string BC_Control1 { get; set; }
        public string BC_X1 { get; set; }
        public string BC_Rot1 { get; set; }
        public string BC_Seal1 { get; set; }
        public string BC_Shaft1 { get; set; }
        public string BC_Flan1 { get; set; }
        public string BC_PB1 { get; set; }
        public string BC_Thdr1 { get; set; }
        public string BC_Prefix { get; set; }
        public string BC_Prefix1 { get; set; }
    }
}
