//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartModelCodeBreakdown
    {
        public int MXID { get; set; }
        public string MX_ModelCode { get; set; }
        public string MX_CorrectedModelCode { get; set; }
        public string MX_Part2 { get; set; }
        public string MX_Part3 { get; set; }
        public string MX_Prefix { get; set; }
        public string MX_Family { get; set; }
        public string MX_Type { get; set; }
        public string MX_Size { get; set; }
        public string MX_Control { get; set; }
        public string MX_AuxOptions { get; set; }
        public string MX_CtrlOptions { get; set; }
        public string MX_POR { get; set; }
        public string MX_NeutralPosSwitch { get; set; }
        public string MX_AngleSensor { get; set; }
        public string MX_StrokeLimiter { get; set; }
        public string MX_X3X4Ports { get; set; }
        public string MX_DAValve { get; set; }
        public string MX_Damping { get; set; }
        public string MX_DispScrew { get; set; }
        public string MX_Series { get; set; }
        public string MX_Threads { get; set; }
        public string MX_Rotation { get; set; }
        public string MX_MinDisp { get; set; }
        public string MX_Dash { get; set; }
        public string MX_Seals { get; set; }
        public string MX_Bearing { get; set; }
        public string MX_Shaft { get; set; }
        public string MX_Flange { get; set; }
        public string MX_PortBlock { get; set; }
        public string MX_BoostPump { get; set; }
        public string MX_ThroughDrive { get; set; }
        public string MX_End { get; set; }
        public string MX_Valve { get; set; }
        public string MX_PortsValve { get; set; }
        public string MX_Filter { get; set; }
        public string MX_Connector { get; set; }
        public string MX_Version { get; set; }
        public string MX_Sensor { get; set; }
        public string MX_SpecialOption { get; set; }
        public string MX_DiscountCombo { get; set; }
        public string MX_Plant { get; set; }
        public string MX_Product { get; set; }
        public string MX_Operation { get; set; }
        public Nullable<int> PARTID { get; set; }
    }
}
