//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrinter
    {
        public tblPrinter()
        {
            this.tblValueMachinePrinter = new HashSet<tblValueMachinePrinter>();
            this.tblValueMachinePCPrinters = new HashSet<tblValueMachinePCPrinters>();
        }
    
        public int PRID { get; set; }
        public string PR_Desc { get; set; }
        public string PR_Long { get; set; }
        public bool PR_Active { get; set; }
        public System.DateTime PR_Created { get; set; }
        public Nullable<System.DateTime> PR_Deleted { get; set; }
    
        public virtual ICollection<tblValueMachinePrinter> tblValueMachinePrinter { get; set; }
        public virtual ICollection<tblValueMachinePCPrinters> tblValueMachinePCPrinters { get; set; }
    }
}
