//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingPart
    {
        public int SHPID { get; set; }
        public int PARTID { get; set; }
        public int SHID { get; set; }
        public Nullable<int> SRCID { get; set; }
        public Nullable<int> SHP_Qty { get; set; }
        public Nullable<System.DateTime> SHP_Deleted { get; set; }
        public string SHP_Line { get; set; }
        public Nullable<System.DateTime> SHP_Shipped { get; set; }
        public Nullable<int> MRPID { get; set; }
        public string SHP_Location { get; set; }
        public string SHP_SSSent { get; set; }
        public string SHP_SSPull { get; set; }
        public string SHP_SSPullOK { get; set; }
        public Nullable<System.DateTime> SHP_PlannedGIDate { get; set; }
        public Nullable<int> SHP_SVPSkip { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblShipping tblShipping { get; set; }
    }
}
