//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsDelivery
    {
        public int SPDID { get; set; }
        public string SPD_Desc { get; set; }
        public bool SPD_Active { get; set; }
        public System.DateTime SPD_Created { get; set; }
        public Nullable<System.DateTime> SPD_Deleted { get; set; }
        public Nullable<int> PARTID { get; set; }
        public Nullable<int> SPD_Qty { get; set; }
        public Nullable<System.DateTime> SPD_Shipped { get; set; }
        public Nullable<System.DateTime> SPD_Picked { get; set; }
        public Nullable<int> ASID { get; set; }
        public Nullable<int> ASID_I { get; set; }
        public Nullable<int> ASID_S { get; set; }
        public Nullable<int> SPDSID { get; set; }
        public Nullable<System.DateTime> SPD_Inspected { get; set; }
        public Nullable<bool> SPD_Changed { get; set; }
        public Nullable<bool> SPD_Issue { get; set; }
        public Nullable<System.DateTime> SPD_Override { get; set; }
        public Nullable<int> ASID_O { get; set; }
        public Nullable<bool> SPD_Claim { get; set; }
    }
}
