//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipping
    {
        public tblShipping()
        {
            this.tblShippingComment = new HashSet<tblShippingComment>();
            this.tblShippingPart = new HashSet<tblShippingPart>();
            this.tblShippingStatus = new HashSet<tblShippingStatus>();
        }
    
        public int SHID { get; set; }
        public Nullable<int> SRCID { get; set; }
        public int CSNID { get; set; }
        public Nullable<int> MRPID { get; set; }
        public Nullable<int> FLDID { get; set; }
        public string SH_Desc { get; set; }
        public System.DateTime SH_Date { get; set; }
        public Nullable<int> SH_Sort { get; set; }
        public Nullable<System.DateTime> SH_Deleted { get; set; }
        public System.DateTime SH_Created { get; set; }
        public string SH_Location { get; set; }
        public Nullable<System.DateTime> SH_ShipDate { get; set; }
        public string SH_SSSent { get; set; }
        public string SH_SSPull { get; set; }
        public bool SH_FromPack { get; set; }
        public Nullable<System.DateTime> SH_PlannedGIDate { get; set; }
    
        public virtual ICollection<tblShippingComment> tblShippingComment { get; set; }
        public virtual ICollection<tblShippingPart> tblShippingPart { get; set; }
        public virtual ICollection<tblShippingStatus> tblShippingStatus { get; set; }
    }
}
