//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingAction
    {
        public tblShippingAction()
        {
            this.tblShippingCommentType = new HashSet<tblShippingCommentType>();
        }
    
        public int SHAID { get; set; }
        public string SHA_Desc { get; set; }
        public int SHA_Active { get; set; }
        public Nullable<System.DateTime> SHA_Deleted { get; set; }
    
        public virtual ICollection<tblShippingCommentType> tblShippingCommentType { get; set; }
    }
}
