//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsDeliveryRole
    {
        public int SPDRID { get; set; }
        public string SPDR_Desc { get; set; }
        public bool SPDR_Active { get; set; }
        public System.DateTime SPDR_Created { get; set; }
        public Nullable<System.DateTime> SPDR_Deleted { get; set; }
        public int PNum { get; set; }
        public Nullable<int> ASID { get; set; }
        public string Initials { get; set; }
    }
}
