//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsInspections
    {
        public int SPIID { get; set; }
        public int SPDID { get; set; }
        public int SPDQID { get; set; }
        public string SPI_Desc { get; set; }
        public bool SPI_Active { get; set; }
        public System.DateTime SPI_Created { get; set; }
        public Nullable<System.DateTime> SPI_Deleted { get; set; }
        public string SPI_Answer { get; set; }
        public Nullable<int> SPI_ASID { get; set; }
    }
}
