//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingDetailStatus
    {
        public tblShippingDetailStatus()
        {
            this.tblShippingStatus = new HashSet<tblShippingStatus>();
        }
    
        public int SHDSID { get; set; }
        public int SHMSID { get; set; }
        public string SHDS_Desc { get; set; }
        public int SHDS_Active { get; set; }
        public string SHDS_SAP { get; set; }
        public int SHDS_Sort { get; set; }
        public Nullable<System.DateTime> SHDS_Deleted { get; set; }
    
        public virtual tblShippingMasterStatus tblShippingMasterStatus { get; set; }
        public virtual ICollection<tblShippingStatus> tblShippingStatus { get; set; }
    }
}
