//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsComments
    {
        public int SPDCID { get; set; }
        public string SPDC_Desc { get; set; }
        public bool SPDC_Active { get; set; }
        public System.DateTime SPDC_Created { get; set; }
        public Nullable<System.DateTime> SPDC_Deleted { get; set; }
        public int SPDID { get; set; }
    }
}
