//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsDeliveryStatus
    {
        public int SPDSID { get; set; }
        public string SPDS_Desc { get; set; }
        public bool SPDS_Active { get; set; }
        public System.DateTime SPDS_Created { get; set; }
        public Nullable<System.DateTime> SPDS_Deleted { get; set; }
    }
}
