//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingReasonCode
    {
        public int SRCID { get; set; }
        public string SRC_Desc { get; set; }
        public Nullable<System.DateTime> SRC_Deleted { get; set; }
    }
}
