//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingStatus
    {
        public int SHSID { get; set; }
        public int SHID { get; set; }
        public int SHDSID { get; set; }
        public System.DateTime SHS_Date { get; set; }
        public Nullable<int> ASID { get; set; }
        public string SHS_Name { get; set; }
        public Nullable<int> FLID { get; set; }
    
        public virtual tblShipping tblShipping { get; set; }
        public virtual tblShippingDetailStatus tblShippingDetailStatus { get; set; }
    }
}
