//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSparePartsInspQuestions
    {
        public int SPDQID { get; set; }
        public string SPDQ_Desc { get; set; }
        public bool SPDQ_Active { get; set; }
        public System.DateTime SPDQ_Created { get; set; }
        public Nullable<System.DateTime> SPDQ_Deleted { get; set; }
    }
}
