//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestStandCycleTime
    {
        public int TSCYID { get; set; }
        public System.DateTime TSCY_Created { get; set; }
        public Nullable<System.DateTime> TSCY_Deleted { get; set; }
        public string TSCY_Part { get; set; }
        public Nullable<decimal> TSCY_Time { get; set; }
        public string TSCY_Family { get; set; }
        public string TSCY_TestStand { get; set; }
    }
}
