//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOpListWC
    {
        public int VNDID { get; set; }
        public int VNID { get; set; }
        public int VWID { get; set; }
        public bool VND_Active { get; set; }
        public System.DateTime VND_Created { get; set; }
        public Nullable<System.DateTime> VND_Deleted { get; set; }
    
        public virtual tblValueMachineOpList tblValueMachineOpList { get; set; }
        public virtual tblValueMachineWC tblValueMachineWC { get; set; }
    }
}
