//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineScrapCode
    {
        public int SAID { get; set; }
        public string SA_Short { get; set; }
        public string SA_Desc { get; set; }
        public bool SA_Active { get; set; }
        public System.DateTime SA_Created { get; set; }
        public Nullable<System.DateTime> SA_Deleted { get; set; }
    }
}
