//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachinePCPrinters
    {
        public int VDID { get; set; }
        public int PRID { get; set; }
        public int PCID { get; set; }
        public bool VD_Active { get; set; }
        public System.DateTime VD_Created { get; set; }
        public Nullable<System.DateTime> VD_Deleted { get; set; }
        public int VD_LabelSort { get; set; }
    
        public virtual tblPrinter tblPrinter { get; set; }
        public virtual tblValueMachinePC tblValueMachinePC { get; set; }
    }
}
