//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineWC_VMID
    {
        public int WMID { get; set; }
        public int VMID { get; set; }
        public bool WM_Active { get; set; }
        public System.DateTime WM_Created { get; set; }
        public Nullable<System.DateTime> WM_Deleted { get; set; }
        public int VWID { get; set; }
    
        public virtual tblValueMachine tblValueMachine { get; set; }
        public virtual tblValueMachineWC tblValueMachineWC { get; set; }
    }
}
