//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineSupplier
    {
        public int VLID { get; set; }
        public string VL_Desc { get; set; }
        public bool VL_Active { get; set; }
        public System.DateTime VL_Created { get; set; }
        public Nullable<System.DateTime> VL_Deleted { get; set; }
    }
}
