//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineWC
    {
        public tblValueMachineWC()
        {
            this.tblValueMachineOpListWC = new HashSet<tblValueMachineOpListWC>();
            this.tblValueMachineOrderOp = new HashSet<tblValueMachineOrderOp>();
            this.tblValueMachineWC_VMID = new HashSet<tblValueMachineWC_VMID>();
            this.tblValueMachineWCSetup = new HashSet<tblValueMachineWCSetup>();
        }
    
        public int VWID { get; set; }
        public int VMID { get; set; }
        public string VW_Desc { get; set; }
        public string VW_Long { get; set; }
        public Nullable<System.DateTime> VW_Deleted { get; set; }
        public Nullable<System.DateTime> VW_TimeStamp { get; set; }
        public Nullable<int> VAID { get; set; }
        public string VW_Short { get; set; }
    
        public virtual tblValueMachine tblValueMachine { get; set; }
        public virtual ICollection<tblValueMachineOpListWC> tblValueMachineOpListWC { get; set; }
        public virtual ICollection<tblValueMachineOrderOp> tblValueMachineOrderOp { get; set; }
        public virtual ICollection<tblValueMachineWC_VMID> tblValueMachineWC_VMID { get; set; }
        public virtual ICollection<tblValueMachineWCSetup> tblValueMachineWCSetup { get; set; }
    }
}
