//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOrderOpManualConfirmErr
    {
        public int VZID { get; set; }
        public int VPID { get; set; }
        public string VZ_Desc { get; set; }
        public string VZ_Host { get; set; }
        public string VZ_User { get; set; }
        public string VZ_Caller { get; set; }
        public System.DateTime VZ_Created { get; set; }
    
        public virtual tblValueMachineOrderOp tblValueMachineOrderOp { get; set; }
    }
}
