//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachinePart
    {
        public int VPID { get; set; }
        public int PARTID { get; set; }
        public int VMID { get; set; }
        public int VP_Primary { get; set; }
        public System.DateTime VP_TimeStamp { get; set; }
        public decimal VP_RunTime { get; set; }
        public Nullable<int> VWID { get; set; }
        public Nullable<System.DateTime> VP_Deleted { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblValueMachine tblValueMachine { get; set; }
    }
}
