//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineCommentType
    {
        public tblValueMachineCommentType()
        {
            this.tblValueMachineOrderComment = new HashSet<tblValueMachineOrderComment>();
        }
    
        public int VMCTID { get; set; }
        public string VMCT_Desc { get; set; }
        public string VMCT_Color { get; set; }
        public Nullable<System.DateTime> VMCT_Deleted { get; set; }
    
        public virtual ICollection<tblValueMachineOrderComment> tblValueMachineOrderComment { get; set; }
    }
}
