//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineSetup
    {
        public tblValueMachineSetup()
        {
            this.tblValueMachinePartSetup = new HashSet<tblValueMachinePartSetup>();
            this.tblValueMachineWCSetup = new HashSet<tblValueMachineWCSetup>();
        }
    
        public int SUPID { get; set; }
        public string SUP_Desc { get; set; }
        public Nullable<System.DateTime> SUP_Deleted { get; set; }
        public System.DateTime SUP_TimeStamp { get; set; }
    
        public virtual ICollection<tblValueMachinePartSetup> tblValueMachinePartSetup { get; set; }
        public virtual ICollection<tblValueMachineWCSetup> tblValueMachineWCSetup { get; set; }
    }
}
