//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineCastings
    {
        public tblValueMachineCastings()
        {
            this.tblValueMachineCastingPart = new HashSet<tblValueMachineCastingPart>();
        }
    
        public int CASTID { get; set; }
        public string CAST_Desc { get; set; }
        public Nullable<System.DateTime> CAST_Deleted { get; set; }
        public Nullable<int> VLID { get; set; }
        public Nullable<int> BLDID { get; set; }
        public Nullable<int> CAST_BoxQty { get; set; }
        public string CAST_KanbanID { get; set; }
        public int CAST_5018Min { get; set; }
    
        public virtual ICollection<tblValueMachineCastingPart> tblValueMachineCastingPart { get; set; }
    }
}
