//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOrder
    {
        public tblValueMachineOrder()
        {
            this.tblValueMachineOrderComment = new HashSet<tblValueMachineOrderComment>();
            this.tblValueMachineOrderOp = new HashSet<tblValueMachineOrderOp>();
        }
    
        public int VOID { get; set; }
        public int VSID { get; set; }
        public Nullable<int> VMID { get; set; }
        public int PARTID { get; set; }
        public string VO_Desc { get; set; }
        public Nullable<int> VO_Qty { get; set; }
        public Nullable<System.DateTime> VO_BSCStart { get; set; }
        public Nullable<System.DateTime> VO_BSCFinish { get; set; }
        public System.DateTime VO_TimeStamp { get; set; }
        public System.DateTime VO_Updated { get; set; }
        public Nullable<int> VO_Sort { get; set; }
        public Nullable<System.DateTime> VO_SortDate { get; set; }
        public Nullable<int> CASTID { get; set; }
        public Nullable<int> SUPID { get; set; }
        public Nullable<System.DateTime> VO_StartDate { get; set; }
        public Nullable<System.DateTime> VO_FinishDate { get; set; }
        public Nullable<bool> VO_Created { get; set; }
        public Nullable<int> VO_DeliveredQty { get; set; }
        public string VO_SAPStatus { get; set; }
        public Nullable<int> VMID_Machining { get; set; }
        public Nullable<int> VO_RunSetup { get; set; }
        public Nullable<decimal> VO_RunTotal { get; set; }
        public Nullable<decimal> VO_RunTotalHR { get; set; }
        public Nullable<System.DateTime> VO_RunStart { get; set; }
        public Nullable<System.DateTime> VO_RunFinish { get; set; }
        public string VO_RunTime { get; set; }
        public Nullable<int> VO_RunSort { get; set; }
        public Nullable<System.DateTime> VO_DeliveredQtyUpdated { get; set; }
        public string VO_Short1 { get; set; }
        public Nullable<System.DateTime> VO_UpdatedVMID { get; set; }
        public Nullable<int> VO_Scrap { get; set; }
        public Nullable<int> VSID_Pre { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblValueStream tblValueStream { get; set; }
        public virtual ICollection<tblValueMachineOrderComment> tblValueMachineOrderComment { get; set; }
        public virtual ICollection<tblValueMachineOrderOp> tblValueMachineOrderOp { get; set; }
    }
}
