//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOrderOpManualConfirm
    {
        public int VVID { get; set; }
        public int ASID { get; set; }
        public int VPID { get; set; }
        public int VQID { get; set; }
        public int VV_Yield { get; set; }
        public int VV_Scrap { get; set; }
        public string VV_OP { get; set; }
        public string VV_WorkCenter { get; set; }
        public string VV_PNum { get; set; }
        public System.DateTime VV_Created { get; set; }
        public Nullable<int> PCID { get; set; }
        public Nullable<int> VMID { get; set; }
        public Nullable<int> PRID { get; set; }
        public Nullable<int> SAID { get; set; }
        public Nullable<int> VYID { get; set; }
        public string VV_Comment { get; set; }
        public byte[] VV_image { get; set; }
    
        public virtual tblValueMachineOrderOpManualConfirm tblValueMachineOrderOpManualConfirm1 { get; set; }
        public virtual tblValueMachineOrderOpManualConfirm tblValueMachineOrderOpManualConfirm2 { get; set; }
    }
}
