//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachinePC
    {
        public tblValueMachinePC()
        {
            this.tblValueMachinePCLink = new HashSet<tblValueMachinePCLink>();
            this.tblValueMachinePCPrinters = new HashSet<tblValueMachinePCPrinters>();
        }
    
        public int PCID { get; set; }
        public string PC_Desc { get; set; }
        public bool PC_Active { get; set; }
        public System.DateTime PC_Created { get; set; }
        public Nullable<System.DateTime> PC_Deleted { get; set; }
        public bool PC_AutoConfirm { get; set; }
        public bool PC_AutoFromPC { get; set; }
    
        public virtual ICollection<tblValueMachinePCLink> tblValueMachinePCLink { get; set; }
        public virtual ICollection<tblValueMachinePCPrinters> tblValueMachinePCPrinters { get; set; }
    }
}
