//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachine
    {
        public tblValueMachine()
        {
            this.tblValueMachineDown = new HashSet<tblValueMachineDown>();
            this.tblValueMachinePart = new HashSet<tblValueMachinePart>();
            this.tblValueMachinePCLink = new HashSet<tblValueMachinePCLink>();
            this.tblValueMachinePrinter = new HashSet<tblValueMachinePrinter>();
            this.tblValueMachineWC = new HashSet<tblValueMachineWC>();
            this.tblValueMachineWC_VMID = new HashSet<tblValueMachineWC_VMID>();
        }
    
        public int VMID { get; set; }
        public string VM_Desc { get; set; }
        public string VM_Short { get; set; }
        public Nullable<int> VM_TotalHours { get; set; }
        public Nullable<System.DateTime> VM_Deleted { get; set; }
        public string VM_Color { get; set; }
        public Nullable<int> ASID1 { get; set; }
        public Nullable<int> ASID2 { get; set; }
        public Nullable<int> ASID3 { get; set; }
        public Nullable<int> ASID4 { get; set; }
        public Nullable<int> ASID5 { get; set; }
        public Nullable<int> BLDID { get; set; }
        public string VM_ManPower { get; set; }
        public string VM_Priority { get; set; }
        public bool VM_Machining { get; set; }
        public Nullable<decimal> VM_AvgRunTime { get; set; }
        public Nullable<int> VSID_Pre { get; set; }
        public Nullable<int> ASIDVOIS { get; set; }
        public string VM_FLoc { get; set; }
        public Nullable<int> VSID_Pre2 { get; set; }
        public Nullable<int> VSID_Pre3 { get; set; }
        public string VM_ProdSupplyArea { get; set; }
    
        public virtual ICollection<tblValueMachineDown> tblValueMachineDown { get; set; }
        public virtual ICollection<tblValueMachinePart> tblValueMachinePart { get; set; }
        public virtual ICollection<tblValueMachinePCLink> tblValueMachinePCLink { get; set; }
        public virtual ICollection<tblValueMachinePrinter> tblValueMachinePrinter { get; set; }
        public virtual ICollection<tblValueMachineWC> tblValueMachineWC { get; set; }
        public virtual ICollection<tblValueMachineWC_VMID> tblValueMachineWC_VMID { get; set; }
    }
}
