//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOrderCastingEmail
    {
        public int VQID { get; set; }
        public System.DateTime VQ_Created { get; set; }
        public string VO_Desc { get; set; }
        public Nullable<System.DateTime> VO_RunStart { get; set; }
        public Nullable<int> VO_Qty { get; set; }
        public Nullable<int> VO_DeliveredQty { get; set; }
        public string Supplier { get; set; }
        public string Casting { get; set; }
        public Nullable<double> BoxQty { get; set; }
        public Nullable<double> OrderQtyTotal { get; set; }
        public Nullable<double> DeliveredQtyTotal { get; set; }
        public Nullable<double> DeltaQtyTotal { get; set; }
        public Nullable<double> OrderBoxes { get; set; }
        public Nullable<int> OrderBoxesRndDown { get; set; }
        public string Building { get; set; }
        public Nullable<double> C5018 { get; set; }
        public Nullable<int> C5018Min { get; set; }
        public Nullable<int> Boxes { get; set; }
        public Nullable<System.DateTime> C5018RunAt { get; set; }
    }
}
