//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOrderStatus
    {
        public int SVID { get; set; }
        public int ASID { get; set; }
        public int VOID { get; set; }
        public int SMID { get; set; }
        public System.DateTime SV_TimeStamp { get; set; }
    }
}
