//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachinePartSetup
    {
        public int SUPTID { get; set; }
        public Nullable<int> SUPID { get; set; }
        public Nullable<int> PARTID { get; set; }
        public System.DateTime SUPT_TimeStamp { get; set; }
        public Nullable<System.DateTime> SUPT_Deleted { get; set; }
        public Nullable<int> VWID { get; set; }
    
        public virtual tblPart tblPart { get; set; }
        public virtual tblValueMachineSetup tblValueMachineSetup { get; set; }
    }
}
