//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachinePrinter
    {
        public int VUID { get; set; }
        public int PRID { get; set; }
        public int VMID { get; set; }
        public bool VU_Active { get; set; }
        public System.DateTime VU_Created { get; set; }
        public Nullable<System.DateTime> VU_Deleted { get; set; }
    
        public virtual tblPrinter tblPrinter { get; set; }
        public virtual tblValueMachine tblValueMachine { get; set; }
    }
}
