//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueStream
    {
        public tblValueStream()
        {
            this.tblValueMachineOrder = new HashSet<tblValueMachineOrder>();
        }
    
        public int VSID { get; set; }
        public int VSGID { get; set; }
        public string VS_Desc { get; set; }
        public string VS_Color { get; set; }
        public int VS_Active { get; set; }
        public Nullable<int> ASID { get; set; }
        public string VS_ForeColor { get; set; }
        public string VS_SAP { get; set; }
        public Nullable<int> VS_Sort { get; set; }
        public Nullable<int> VS_TAKT { get; set; }
        public bool VS_DSB { get; set; }
        public bool VS_UseDSTID { get; set; }
        public Nullable<bool> VS_QVS { get; set; }
        public Nullable<bool> VS_MDB { get; set; }
        public Nullable<bool> VS_LogPickScreen { get; set; }
        public Nullable<bool> VS_Andon { get; set; }
        public Nullable<System.DateTime> VS_Added { get; set; }
    
        public virtual ICollection<tblValueMachineOrder> tblValueMachineOrder { get; set; }
    }
}
