//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOpList
    {
        public tblValueMachineOpList()
        {
            this.tblValueMachineOpListWC = new HashSet<tblValueMachineOpListWC>();
            this.tblValueMachineOrderOp = new HashSet<tblValueMachineOrderOp>();
        }
    
        public int VNID { get; set; }
        public string VN_Desc { get; set; }
        public Nullable<System.DateTime> VN_Deleted { get; set; }
        public System.DateTime VN_TimeStamp { get; set; }
        public Nullable<int> VAID { get; set; }
        public string VN_Operation { get; set; }
    
        public virtual ICollection<tblValueMachineOpListWC> tblValueMachineOpListWC { get; set; }
        public virtual ICollection<tblValueMachineOrderOp> tblValueMachineOrderOp { get; set; }
    }
}
