//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineReasonCodes
    {
        public int VMCID { get; set; }
        public string VMC_Desc { get; set; }
        public bool VMC_Active { get; set; }
        public System.DateTime VMC_Created { get; set; }
        public Nullable<System.DateTime> VMC_Deleted { get; set; }
    }
}
