//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineHealth
    {
        public int MHID { get; set; }
        public string MH_1 { get; set; }
        public string MH_2 { get; set; }
        public string MH_3 { get; set; }
        public string MH_4 { get; set; }
    }
}
