//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblValueMachineOpArea
    {
        public int VAID { get; set; }
        public string VA_Desc { get; set; }
        public bool VA_Active { get; set; }
        public System.DateTime VA_Created { get; set; }
        public Nullable<System.DateTime> VA_Deleted { get; set; }
    }
}
