//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKitterAudited
    {
        public Nullable<int> ASID { get; set; }
        public string WorkOrder { get; set; }
        public string KitterBadge { get; set; }
        public string Status { get; set; }
        public Nullable<int> KIID { get; set; }
        public Nullable<int> WOID { get; set; }
        public string ValueStream { get; set; }
        public Nullable<bool> KI_Good { get; set; }
        public string AuditorBadge { get; set; }
        public string AuditError { get; set; }
        public string KitterName { get; set; }
        public Nullable<int> KitterCount { get; set; }
        public Nullable<System.DateTime> KittedTime { get; set; }
        public Nullable<int> AuditorCount { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<int> AU_ASID { get; set; }
        public string AU_Comment { get; set; }
        public string AuditorName { get; set; }
    }
}
