//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKitter
    {
        public Nullable<int> ASID { get; set; }
        public string WorkOrder { get; set; }
        public string Name { get; set; }
        public string KitterBadge { get; set; }
        public string Status { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> KIID { get; set; }
        public Nullable<int> WOID { get; set; }
        public string ValueStream { get; set; }
        public Nullable<bool> KI_Good { get; set; }
        public int KLID { get; set; }
        public int KSID { get; set; }
        public Nullable<int> WkHour { get; set; }
        public string AS_Display { get; set; }
    }
}
