//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPartBOM
    {
        public int BPID { get; set; }
        public string PART_Desc { get; set; }
        public System.DateTime BP_Created { get; set; }
        public System.DateTime BP_Updated { get; set; }
    }
}
