//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPartRineerMatch2
    {
        public int PARTID { get; set; }
        public string PPZ_Desc { get; set; }
        public string PSR_Desc { get; set; }
        public string PPT_Desc { get; set; }
        public string PPK_Desc { get; set; }
        public string PDP_Desc { get; set; }
        public string PSF_Desc { get; set; }
        public string PSB_Desc { get; set; }
        public string PSL_Desc { get; set; }
        public string PSP_Desc { get; set; }
    }
}
