//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPartBOM_Details
    {
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public int PARTID { get; set; }
        public int BPPID { get; set; }
        public int BPID { get; set; }
        public string PTS_Lev { get; set; }
        public string PTS_Item { get; set; }
        public string PTS_ICt { get; set; }
        public string PTS_Component { get; set; }
        public string PTS_Asm { get; set; }
        public string PTS_PrcoType { get; set; }
        public string PTS_SPT { get; set; }
        public string PTS_MatDoc { get; set; }
        public string PTS_MatDescription { get; set; }
        public Nullable<System.DateTime> PTS_ValidFrom { get; set; }
        public Nullable<System.DateTime> PTS_ValidTo { get; set; }
        public string PTS_ChangeNo { get; set; }
        public Nullable<System.DateTime> PTS_TimeStamp { get; set; }
        public string Fam { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Control { get; set; }
        public string C_X { get; set; }
        public string Rot { get; set; }
        public string Seal { get; set; }
        public string Shaft { get; set; }
        public string Flan { get; set; }
        public string PB { get; set; }
        public string Thdr { get; set; }
        public string Pre { get; set; }
        public string Two { get; set; }
        public string Three { get; set; }
    }
}
