//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPartBomValueStream
    {
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public string VS_Desc { get; set; }
        public int PARTID { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public int VSID { get; set; }
    }
}
