//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPartFolderSHID
    {
        public int SHID { get; set; }
        public byte[] PTPT_PDFImage { get; set; }
        public int Expr1 { get; set; }
        public int PARTID { get; set; }
        public int PTPTID { get; set; }
        public string PART_Desc { get; set; }
        public string PTPT_Name { get; set; }
        public string PTFLD_Desc { get; set; }
    }
}
