//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSerialPartWO
    {
        public string PART_Desc { get; set; }
        public string WO_Desc { get; set; }
        public Nullable<int> VSID { get; set; }
        public int PartID { get; set; }
        public Nullable<int> WOID { get; set; }
        public string PART_TX { get; set; }
        public int Serial { get; set; }
        public Nullable<int> WO_Qty { get; set; }
        public string BatchNo { get; set; }
    }
}
