//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShippingComments
    {
        public string SHCT_Desc { get; set; }
        public string SHC_Comment { get; set; }
        public System.DateTime SHC_Date { get; set; }
        public string Associate { get; set; }
        public int SHID { get; set; }
        public int SHCID { get; set; }
        public Nullable<int> SHPID { get; set; }
    }
}
