//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShippingStatus
    {
        public string SH_Desc { get; set; }
        public Nullable<int> SH_Sort { get; set; }
        public Nullable<System.DateTime> SH_Deleted { get; set; }
        public int SHID { get; set; }
        public Nullable<int> FLDID { get; set; }
        public string SH_Location { get; set; }
        public Nullable<System.DateTime> SH_ShipDate { get; set; }
        public string SH_SSSent { get; set; }
        public string SH_SSPull { get; set; }
        public string SH_Date { get; set; }
        public string SRC_Desc { get; set; }
        public int SHPID { get; set; }
        public Nullable<int> SHP_Qty { get; set; }
        public Nullable<System.DateTime> SHP_Shipped { get; set; }
        public Nullable<int> SRCID { get; set; }
        public string SHP_Location { get; set; }
        public string SHP_Line { get; set; }
        public string SHP_SSSent { get; set; }
        public string SHP_SSPull { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public int PARTID { get; set; }
        public string COMAT_GoTo { get; set; }
        public Nullable<int> MPTID { get; set; }
        public string MPT_Desc { get; set; }
        public int MRP_Type { get; set; }
        public string MRP_Number { get; set; }
        public string CSN_Desc { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public System.DateTime SHS_Date { get; set; }
        public int SHDSID { get; set; }
        public int SHSID { get; set; }
        public string SHDS_Desc { get; set; }
        public int SHMSID { get; set; }
        public string SHMS_Desc { get; set; }
        public string RushComment { get; set; }
        public int Rushed { get; set; }
        public string CSR { get; set; }
        public string LOG2 { get; set; }
        public Nullable<int> SHCID { get; set; }
        public Nullable<int> SHCTID { get; set; }
        public Nullable<int> SHAID { get; set; }
        public Nullable<int> SHCT_Color { get; set; }
        public Nullable<int> SHCT_ForeColor { get; set; }
        public string SHCT_Desc { get; set; }
        public Nullable<System.DateTime> SHC_Date { get; set; }
        public string SHC_Comment { get; set; }
        public string SHP_SSPullOK { get; set; }
        public string CSN_Long { get; set; }
        public Nullable<System.DateTime> SHP_PlannedGIDate { get; set; }
        public Nullable<int> SHP_SVPSkip { get; set; }
    }
}
