//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShippingStatusHistory
    {
        public string SHMS_Desc { get; set; }
        public string SHDS_Desc { get; set; }
        public System.DateTime SHS_Date { get; set; }
        public string Associate { get; set; }
        public int SHSID { get; set; }
        public int SHID { get; set; }
    }
}
