//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSparePartsInspectionsSumUp
    {
        public int SPDID { get; set; }
        public Nullable<int> Pre_Packed { get; set; }
        public Nullable<int> No_Rust { get; set; }
        public Nullable<int> No_Damage { get; set; }
        public Nullable<int> Correct_Qty { get; set; }
        public Nullable<int> Correct_PN { get; set; }
        public Nullable<int> Correct_Desc { get; set; }
        public Nullable<int> Complete { get; set; }
    }
}
