//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSparePartsInspectionsTotals
    {
        public Nullable<int> ASID { get; set; }
        public string SPD_Desc { get; set; }
        public System.DateTime SPD_Created { get; set; }
        public Nullable<System.DateTime> SPD_Picked { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> SPD_Inspected { get; set; }
        public Nullable<int> Pre_Packed { get; set; }
        public Nullable<int> No_Rust { get; set; }
        public Nullable<int> No_Damage { get; set; }
        public Nullable<int> Correct_Qty { get; set; }
        public Nullable<int> Correct_PN { get; set; }
        public Nullable<int> Correct_Desc { get; set; }
        public Nullable<int> Complete { get; set; }
        public Nullable<int> ASID_I { get; set; }
        public Nullable<System.DateTime> SPD_Override { get; set; }
        public Nullable<int> ASID_O { get; set; }
        public Nullable<int> SPDSID { get; set; }
        public string SPDC_Desc { get; set; }
        public int SPDID { get; set; }
        public Nullable<bool> SPD_Claim { get; set; }
        public Nullable<bool> SPD_Issue { get; set; }
    }
}
