//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineDown
    {
        public int VMDID { get; set; }
        public int VMCID { get; set; }
        public int VMID { get; set; }
        public int ASID { get; set; }
        public string VMD_Comment { get; set; }
        public bool VMD_Active { get; set; }
        public System.DateTime VMD_Created { get; set; }
        public Nullable<System.DateTime> VMD_Deleted { get; set; }
        public Nullable<System.DateTime> VMD_Resolved { get; set; }
        public string VM_Desc { get; set; }
        public string VM_Short { get; set; }
        public string VMC_Desc { get; set; }
        public string Associate { get; set; }
        public string Associate2 { get; set; }
        public string lnkBackUp { get; set; }
        public Nullable<int> VMD_Priority { get; set; }
        public string BLD_Desc { get; set; }
    }
}
