//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderManualConfirmLog_Last
    {
        public int LYID { get; set; }
        public int VVID { get; set; }
        public int VQID { get; set; }
        public System.DateTime LY_Created { get; set; }
        public Nullable<long> row { get; set; }
        public Nullable<long> Rank { get; set; }
        public string VQ_Desc { get; set; }
    }
}
