//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderOpCon_SAP
    {
        public int VPID { get; set; }
        public Nullable<int> Confimred { get; set; }
        public int Scrapped { get; set; }
        public Nullable<System.DateTime> LastConfirm { get; set; }
        public int VOID { get; set; }
        public Nullable<int> VMID { get; set; }
        public string VO_Desc { get; set; }
        public string VP_OpOrder { get; set; }
        public int VO_QTY { get; set; }
        public Nullable<int> YieldQued { get; set; }
        public Nullable<int> ScrapQued { get; set; }
    }
}
