//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderLostCapacity
    {
        public Nullable<System.DateTime> LostDate { get; set; }
        public int VOID { get; set; }
        public Nullable<int> VMID { get; set; }
        public string VO_Desc { get; set; }
        public Nullable<int> VO_Qty { get; set; }
        public Nullable<int> VO_DeliveredQty { get; set; }
        public decimal RunTime { get; set; }
        public Nullable<System.DateTime> VO_RunStart { get; set; }
        public Nullable<System.DateTime> VO_RunFinish { get; set; }
        public Nullable<int> VO_RunSetup { get; set; }
        public Nullable<decimal> VO_RunTotal { get; set; }
        public Nullable<decimal> VO_RunTotalHR { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string VM_Desc { get; set; }
        public string VM_Short { get; set; }
        public string VS_Desc { get; set; }
        public int VSID { get; set; }
        public string PART_Desc { get; set; }
    }
}
