//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderManualConfirm
    {
        public string VO_Desc { get; set; }
        public string VM_Desc { get; set; }
        public string VN_Desc { get; set; }
        public string VW_Desc { get; set; }
        public string VW_Short { get; set; }
        public string VP_OpOrder { get; set; }
        public int VOID { get; set; }
        public string VS_Desc { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public int VVID { get; set; }
        public int ASID { get; set; }
        public int VPID { get; set; }
        public int VV_Yield { get; set; }
        public int VV_Scrap { get; set; }
        public string VV_OP { get; set; }
        public string VV_WorkCenter { get; set; }
        public string VV_PNum { get; set; }
        public System.DateTime VV_Created { get; set; }
        public int VQID { get; set; }
        public string SA_Short { get; set; }
        public string PC_Desc { get; set; }
        public Nullable<int> PCID { get; set; }
        public Nullable<int> VMID { get; set; }
        public Nullable<int> SAID { get; set; }
        public string VV_Comment { get; set; }
        public byte[] VV_image { get; set; }
        public System.DateTime LY_Created { get; set; }
        public string VQ_Desc { get; set; }
        public Nullable<int> YieldQued { get; set; }
        public Nullable<int> ScrapQued { get; set; }
    }
}
