//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderManualConfirmErr
    {
        public string VO_Desc { get; set; }
        public string VN_Desc { get; set; }
        public string VW_Desc { get; set; }
        public string VW_Short { get; set; }
        public int VPID { get; set; }
        public string VP_OpOrder { get; set; }
        public int VOID { get; set; }
        public string VS_Desc { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public string VM_Desc { get; set; }
        public int VZID { get; set; }
        public int Expr1 { get; set; }
        public string VZ_Desc { get; set; }
        public string VZ_Host { get; set; }
        public string VZ_User { get; set; }
        public string VZ_Caller { get; set; }
        public System.DateTime VZ_Created { get; set; }
    }
}
