//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderOpManualConfirmQUE
    {
        public int VPID { get; set; }
        public Nullable<int> YieldQued { get; set; }
        public Nullable<int> ScrapQued { get; set; }
    }
}
