//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrderOp
    {
        public string VO_Desc { get; set; }
        public string VN_Desc { get; set; }
        public string VW_Desc { get; set; }
        public string VW_Short { get; set; }
        public int VPID { get; set; }
        public Nullable<System.DateTime> VP_StartDate { get; set; }
        public Nullable<System.DateTime> VP_FinishDate { get; set; }
        public System.DateTime VP_TimeStamp { get; set; }
        public System.DateTime VP_Updated { get; set; }
        public Nullable<decimal> VP_ProcessingTime { get; set; }
        public string VP_ProcessingMin { get; set; }
        public string VP_OpOrder { get; set; }
        public string VP_SAPStatus { get; set; }
        public int VOID { get; set; }
        public int VWID { get; set; }
        public int VNID { get; set; }
        public string VS_Desc { get; set; }
        public Nullable<int> VO_Qty { get; set; }
        public Nullable<System.DateTime> VO_BSCStart { get; set; }
        public Nullable<System.DateTime> VO_BSCFinish { get; set; }
        public System.DateTime VO_TimeStamp { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public string SUP_Desc { get; set; }
        public string CAST_Desc { get; set; }
        public string SM_Desc { get; set; }
        public Nullable<System.DateTime> SV_TimeStamp { get; set; }
        public string VM_Desc { get; set; }
        public string VM_Color { get; set; }
        public Nullable<int> VP_Yield { get; set; }
        public Nullable<int> VP_OpSort { get; set; }
        public Nullable<int> VMID_Machining { get; set; }
        public string VM_DescDSB { get; set; }
        public Nullable<int> VP_PrintAttempts { get; set; }
        public string VS_Desc_Pre { get; set; }
        public Nullable<int> VMID { get; set; }
    }
}
