//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachinePartCrossExt
    {
        public int PARTID { get; set; }
        public Nullable<int> VMID1 { get; set; }
        public string VM_Desc1 { get; set; }
        public Nullable<int> VMID2 { get; set; }
        public string VM_Desc2 { get; set; }
        public Nullable<int> VMID3 { get; set; }
        public string VM_Desc3 { get; set; }
        public Nullable<int> VMID4 { get; set; }
        public string VM_Desc4 { get; set; }
        public string VM_Color1 { get; set; }
        public string VM_Color2 { get; set; }
        public string VM_Color3 { get; set; }
        public string VM_Color4 { get; set; }
        public int VM_TotalHours1 { get; set; }
        public int VM_TotalHours2 { get; set; }
        public int VM_TotalHours3 { get; set; }
        public int VM_TotalHours4 { get; set; }
        public Nullable<decimal> RunTime1 { get; set; }
        public Nullable<decimal> RunTime2 { get; set; }
        public Nullable<decimal> RunTime3 { get; set; }
        public Nullable<decimal> RunTime4 { get; set; }
    }
}
