//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineOrder
    {
        public string VS_Desc { get; set; }
        public string VO_Desc { get; set; }
        public Nullable<int> VO_Qty { get; set; }
        public Nullable<System.DateTime> VO_BSCStart { get; set; }
        public Nullable<System.DateTime> VO_BSCFinish { get; set; }
        public int VSID { get; set; }
        public int PARTID { get; set; }
        public System.DateTime VO_TimeStamp { get; set; }
        public string PART_Desc { get; set; }
        public string PART_TX { get; set; }
        public string CAST_Desc { get; set; }
        public string SUP_Desc { get; set; }
        public int VOID { get; set; }
        public Nullable<int> CASTID { get; set; }
        public Nullable<int> SUPID { get; set; }
        public string SM_Desc { get; set; }
        public Nullable<System.DateTime> VO_SortDate { get; set; }
        public Nullable<int> VO_Sort { get; set; }
        public Nullable<System.DateTime> SV_TimeStamp { get; set; }
        public Nullable<int> SMID { get; set; }
        public string VM_Desc { get; set; }
        public string VM_Color { get; set; }
        public Nullable<int> VMID { get; set; }
        public string CurrentOp { get; set; }
        public Nullable<System.DateTime> LastFinishDate { get; set; }
        public decimal VP_ProcessingTime { get; set; }
        public Nullable<int> VNID { get; set; }
        public string VOC_Comment { get; set; }
        public Nullable<int> VOCID { get; set; }
        public string VMCT_Desc { get; set; }
        public string VMCT_Color { get; set; }
        public string CommentAssociate { get; set; }
        public decimal RunTime { get; set; }
        public Nullable<System.DateTime> VO_StartDate { get; set; }
        public Nullable<System.DateTime> VO_FinishDate { get; set; }
        public Nullable<bool> VO_Created { get; set; }
        public Nullable<int> VAID { get; set; }
        public string VA_Desc { get; set; }
        public Nullable<int> VWID { get; set; }
        public string VW_Short { get; set; }
        public string VW_Desc { get; set; }
        public string VW_Long { get; set; }
        public string VO_CreatedPlus { get; set; }
        public Nullable<System.DateTime> VSP_Date { get; set; }
        public string VP_SAPStatus { get; set; }
        public Nullable<int> VO_DeliveredQty { get; set; }
        public string BLD_Desc { get; set; }
        public Nullable<int> BLDID { get; set; }
        public string BLD_Long { get; set; }
        public string VM_ManPower { get; set; }
        public string VM_Priority { get; set; }
        public string CastingBuilding { get; set; }
        public Nullable<int> BLDIDCast { get; set; }
        public Nullable<int> VMID_Machining { get; set; }
        public Nullable<int> VO_RunSetup { get; set; }
        public Nullable<decimal> VO_RunTotal { get; set; }
        public Nullable<decimal> VO_RunTotalHR { get; set; }
        public Nullable<System.DateTime> VO_RunStart { get; set; }
        public Nullable<System.DateTime> VO_RunFinish { get; set; }
        public string VO_RunTime { get; set; }
        public Nullable<int> VO_RunSort { get; set; }
        public string VO_Short1 { get; set; }
        public Nullable<int> VMCTID { get; set; }
        public Nullable<bool> VM_Machining { get; set; }
        public string PV_Rev { get; set; }
        public Nullable<System.DateTime> PV_Created { get; set; }
        public Nullable<int> VPID { get; set; }
        public Nullable<int> YieldQued { get; set; }
        public Nullable<int> ScrapQued { get; set; }
        public string PV_Rev2 { get; set; }
        public Nullable<System.DateTime> LastOrdered { get; set; }
        public Nullable<int> Samples { get; set; }
        public Nullable<System.DateTime> LastSampleDate { get; set; }
        public Nullable<int> VP_Scrap { get; set; }
        public string VS_Desc_Pre { get; set; }
    }
}
