//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachineComment_History
    {
        public int VOID { get; set; }
        public System.DateTime VOC_TimeStamp { get; set; }
        public string VMCT_Desc { get; set; }
        public string AS_Display { get; set; }
        public string VOC_Comment { get; set; }
    }
}
