//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachinePartCast_Search
    {
        public int PARTID { get; set; }
        public string PART_Desc { get; set; }
        public string CAST_Desc { get; set; }
        public string VM_Desc { get; set; }
        public Nullable<int> BLDID { get; set; }
        public string VS_Desc { get; set; }
        public string PART_TX { get; set; }
    }
}
