//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visual
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwValueMachinePartCross
    {
        public int PARTID { get; set; }
        public Nullable<int> VMID1 { get; set; }
        public Nullable<int> VMID2 { get; set; }
        public Nullable<int> VMID3 { get; set; }
        public Nullable<int> VMID4 { get; set; }
        public Nullable<decimal> RunTime1 { get; set; }
        public Nullable<decimal> RunTime2 { get; set; }
        public Nullable<decimal> RunTime3 { get; set; }
        public Nullable<decimal> RunTime4 { get; set; }
        public string PartNum { get; set; }
        public Nullable<int> CASTID { get; set; }
        public string CAST_Desc { get; set; }
        public Nullable<int> VMID5 { get; set; }
        public Nullable<int> VMID6 { get; set; }
        public Nullable<int> VMID7 { get; set; }
        public Nullable<int> VMID8 { get; set; }
        public Nullable<int> VMID9 { get; set; }
        public Nullable<int> VMID10 { get; set; }
        public Nullable<decimal> RunTime5 { get; set; }
        public Nullable<decimal> RunTime6 { get; set; }
        public Nullable<decimal> RunTime7 { get; set; }
        public Nullable<decimal> RunTime8 { get; set; }
        public Nullable<decimal> RunTime9 { get; set; }
        public Nullable<decimal> RunTime10 { get; set; }
        public string VS_Desc { get; set; }
        public Nullable<int> VSID { get; set; }
        public string PART_TX { get; set; }
    }
}
