

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class HRLEntities : DbContext
{
    public HRLEntities()
        : base("name=HRLEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblApp> tblApp { get; set; }

    public virtual DbSet<tblAppButton> tblAppButton { get; set; }

    public virtual DbSet<tblAppColumnOption> tblAppColumnOption { get; set; }

    public virtual DbSet<tblAppColumns> tblAppColumns { get; set; }

    public virtual DbSet<tblAppErrorLog> tblAppErrorLog { get; set; }

    public virtual DbSet<tblAppFilter> tblAppFilter { get; set; }

    public virtual DbSet<tblAppNavigation> tblAppNavigation { get; set; }

    public virtual DbSet<tblAppNavigationUser> tblAppNavigationUser { get; set; }

    public virtual DbSet<tblAppNavigationUserGrid> tblAppNavigationUserGrid { get; set; }

    public virtual DbSet<tblAppNavMoreButton> tblAppNavMoreButton { get; set; }

    public virtual DbSet<tblAppOptions> tblAppOptions { get; set; }

    public virtual DbSet<tblAppPath> tblAppPath { get; set; }

    public virtual DbSet<tblAppReport> tblAppReport { get; set; }

    public virtual DbSet<tblAppReportOption> tblAppReportOption { get; set; }

    public virtual DbSet<tblAppRole> tblAppRole { get; set; }

    public virtual DbSet<tblAppRoleButtons> tblAppRoleButtons { get; set; }

    public virtual DbSet<tblAppRoles> tblAppRoles { get; set; }

    public virtual DbSet<tblAppTraining> tblAppTraining { get; set; }

    public virtual DbSet<tblAppUser> tblAppUser { get; set; }

    public virtual DbSet<tblEmailDistribution> tblEmailDistribution { get; set; }

    public virtual DbSet<tblEmailDistributionDetail> tblEmailDistributionDetail { get; set; }

    public virtual DbSet<tblFilePath> tblFilePath { get; set; }

    public virtual DbSet<tblFileType> tblFileType { get; set; }

    public virtual DbSet<tblOptions> tblOptions { get; set; }

    public virtual DbSet<tblShift> tblShift { get; set; }

    public virtual DbSet<tblAssociate> tblAssociate { get; set; }

    public virtual DbSet<vwAppButton> vwAppButton { get; set; }

    public virtual DbSet<vwAppColumnFilter> vwAppColumnFilter { get; set; }

    public virtual DbSet<vwAppColumnFilterClear> vwAppColumnFilterClear { get; set; }

    public virtual DbSet<vwAppColumnFilterFields> vwAppColumnFilterFields { get; set; }

    public virtual DbSet<vwAppFilterHelper> vwAppFilterHelper { get; set; }

    public virtual DbSet<vwAppNav> vwAppNav { get; set; }

    public virtual DbSet<vwAppNavigation> vwAppNavigation { get; set; }

    public virtual DbSet<vwAppView> vwAppView { get; set; }

    public virtual DbSet<vwAppView2> vwAppView2 { get; set; }

    public virtual DbSet<vwAssociate> vwAssociate { get; set; }

    public virtual DbSet<vwEmailDistribution> vwEmailDistribution { get; set; }

    public virtual DbSet<Nums> Nums { get; set; }

    public virtual DbSet<tblAppDropDown> tblAppDropDown { get; set; }

    public virtual DbSet<tblPBProxy> tblPBProxy { get; set; }

    public virtual DbSet<vwPBTracking> vwPBTracking { get; set; }

    public virtual DbSet<tblDriverCompany> tblDriverCompany { get; set; }

    public virtual DbSet<tblDriverName> tblDriverName { get; set; }

    public virtual DbSet<tblDriverLog> tblDriverLog { get; set; }

    public virtual DbSet<vwDriverLog> vwDriverLog { get; set; }


    public virtual ObjectResult<p_AddColumns_Result> p_AddColumns(string nAVID, string gRID)
    {

        var nAVIDParameter = nAVID != null ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(string));


        var gRIDParameter = gRID != null ?
            new ObjectParameter("GRID", gRID) :
            new ObjectParameter("GRID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_AddColumns_Result>("p_AddColumns", nAVIDParameter, gRIDParameter);
    }


    public virtual int p_AddDataRow(Nullable<int> aPPID, Nullable<int> nAVID, string user, Nullable<int> miscID, ObjectParameter err, ObjectParameter pK1, ObjectParameter pK2)
    {

        var aPPIDParameter = aPPID.HasValue ?
            new ObjectParameter("APPID", aPPID) :
            new ObjectParameter("APPID", typeof(int));


        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        var miscIDParameter = miscID.HasValue ?
            new ObjectParameter("MiscID", miscID) :
            new ObjectParameter("MiscID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_AddDataRow", aPPIDParameter, nAVIDParameter, userParameter, miscIDParameter, err, pK1, pK2);
    }


    public virtual int p_AddFilterColumns(string nAVID)
    {

        var nAVIDParameter = nAVID != null ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_AddFilterColumns", nAVIDParameter);
    }


    public virtual int p_AppMenuNew(Nullable<int> aPPID, Nullable<int> aSID)
    {

        var aPPIDParameter = aPPID.HasValue ?
            new ObjectParameter("APPID", aPPID) :
            new ObjectParameter("APPID", typeof(int));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_AppMenuNew", aPPIDParameter, aSIDParameter);
    }


    public virtual ObjectResult<p_AppUser_Result> p_AppUser(Nullable<int> aPPID, Nullable<int> nAVID, string appText, string user, Nullable<int> aSID)
    {

        var aPPIDParameter = aPPID.HasValue ?
            new ObjectParameter("APPID", aPPID) :
            new ObjectParameter("APPID", typeof(int));


        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var appTextParameter = appText != null ?
            new ObjectParameter("AppText", appText) :
            new ObjectParameter("AppText", typeof(string));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_AppUser_Result>("p_AppUser", aPPIDParameter, nAVIDParameter, appTextParameter, userParameter, aSIDParameter);
    }


    public virtual ObjectResult<p_CredoMinSelect_Result> p_CredoMinSelect(Nullable<int> nAVID, Nullable<int> pK, string dataGrid, string user)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var pKParameter = pK.HasValue ?
            new ObjectParameter("PK", pK) :
            new ObjectParameter("PK", typeof(int));


        var dataGridParameter = dataGrid != null ?
            new ObjectParameter("DataGrid", dataGrid) :
            new ObjectParameter("DataGrid", typeof(string));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_CredoMinSelect_Result>("p_CredoMinSelect", nAVIDParameter, pKParameter, dataGridParameter, userParameter);
    }


    public virtual ObjectResult<p_DropDown_Result> p_DropDown(Nullable<int> aPPID, Nullable<int> nAVID, string dDL, string user, Nullable<int> aSID)
    {

        var aPPIDParameter = aPPID.HasValue ?
            new ObjectParameter("APPID", aPPID) :
            new ObjectParameter("APPID", typeof(int));


        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var dDLParameter = dDL != null ?
            new ObjectParameter("DDL", dDL) :
            new ObjectParameter("DDL", typeof(string));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_DropDown_Result>("p_DropDown", aPPIDParameter, nAVIDParameter, dDLParameter, userParameter, aSIDParameter);
    }


    public virtual ObjectResult<p_DropDownFilter_Result> p_DropDownFilter(Nullable<int> nAVID, string dDL, string user, string fld, Nullable<int> aSID)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var dDLParameter = dDL != null ?
            new ObjectParameter("DDL", dDL) :
            new ObjectParameter("DDL", typeof(string));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        var fldParameter = fld != null ?
            new ObjectParameter("Fld", fld) :
            new ObjectParameter("Fld", typeof(string));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_DropDownFilter_Result>("p_DropDownFilter", nAVIDParameter, dDLParameter, userParameter, fldParameter, aSIDParameter);
    }


    public virtual ObjectResult<p_DropDownFilter2_Result> p_DropDownFilter2(Nullable<int> nAVID, string dDL, string user, string fld, Nullable<int> aSID)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var dDLParameter = dDL != null ?
            new ObjectParameter("DDL", dDL) :
            new ObjectParameter("DDL", typeof(string));


        var userParameter = user != null ?
            new ObjectParameter("User", user) :
            new ObjectParameter("User", typeof(string));


        var fldParameter = fld != null ?
            new ObjectParameter("Fld", fld) :
            new ObjectParameter("Fld", typeof(string));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_DropDownFilter2_Result>("p_DropDownFilter2", nAVIDParameter, dDLParameter, userParameter, fldParameter, aSIDParameter);
    }


    public virtual ObjectResult<p_DropDownList_Result> p_DropDownList(string fld, string app, string opt2, string opt3)
    {

        var fldParameter = fld != null ?
            new ObjectParameter("Fld", fld) :
            new ObjectParameter("Fld", typeof(string));


        var appParameter = app != null ?
            new ObjectParameter("App", app) :
            new ObjectParameter("App", typeof(string));


        var opt2Parameter = opt2 != null ?
            new ObjectParameter("Opt2", opt2) :
            new ObjectParameter("Opt2", typeof(string));


        var opt3Parameter = opt3 != null ?
            new ObjectParameter("Opt3", opt3) :
            new ObjectParameter("Opt3", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_DropDownList_Result>("p_DropDownList", fldParameter, appParameter, opt2Parameter, opt3Parameter);
    }


    public virtual int p_tblAppErrorLog_Add(string error, Nullable<int> nAVID, Nullable<int> num, string machineName, string userName, string proc)
    {

        var errorParameter = error != null ?
            new ObjectParameter("Error", error) :
            new ObjectParameter("Error", typeof(string));


        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var numParameter = num.HasValue ?
            new ObjectParameter("Num", num) :
            new ObjectParameter("Num", typeof(int));


        var machineNameParameter = machineName != null ?
            new ObjectParameter("MachineName", machineName) :
            new ObjectParameter("MachineName", typeof(string));


        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));


        var procParameter = proc != null ?
            new ObjectParameter("Proc", proc) :
            new ObjectParameter("Proc", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppErrorLog_Add", errorParameter, nAVIDParameter, numParameter, machineNameParameter, userNameParameter, procParameter);
    }


    public virtual int p_tblAppFilter(string token, Nullable<int> nAVID, string grid, string opt)
    {

        var tokenParameter = token != null ?
            new ObjectParameter("Token", token) :
            new ObjectParameter("Token", typeof(string));


        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var gridParameter = grid != null ?
            new ObjectParameter("Grid", grid) :
            new ObjectParameter("Grid", typeof(string));


        var optParameter = opt != null ?
            new ObjectParameter("Opt", opt) :
            new ObjectParameter("Opt", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppFilter", tokenParameter, nAVIDParameter, gridParameter, optParameter);
    }


    public virtual int p_tblAppFilterWhereClause(string token, ObjectParameter strWhere)
    {

        var tokenParameter = token != null ?
            new ObjectParameter("Token", token) :
            new ObjectParameter("Token", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppFilterWhereClause", tokenParameter, strWhere);
    }


    public virtual int p_tblAppNavigationUser_Add(Nullable<int> nAVID, Nullable<int> aSID, string aG_FormItem, Nullable<int> aG_Height, Nullable<int> aG_Width)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        var aG_FormItemParameter = aG_FormItem != null ?
            new ObjectParameter("AG_FormItem", aG_FormItem) :
            new ObjectParameter("AG_FormItem", typeof(string));


        var aG_HeightParameter = aG_Height.HasValue ?
            new ObjectParameter("AG_Height", aG_Height) :
            new ObjectParameter("AG_Height", typeof(int));


        var aG_WidthParameter = aG_Width.HasValue ?
            new ObjectParameter("AG_Width", aG_Width) :
            new ObjectParameter("AG_Width", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppNavigationUser_Add", nAVIDParameter, aSIDParameter, aG_FormItemParameter, aG_HeightParameter, aG_WidthParameter);
    }


    public virtual int p_tblAppNavigationUserGrid_Add(Nullable<int> nAVID, Nullable<int> aSID, Nullable<int> aPCID, Nullable<int> aD_Width, Nullable<int> aD_Sort)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        var aPCIDParameter = aPCID.HasValue ?
            new ObjectParameter("APCID", aPCID) :
            new ObjectParameter("APCID", typeof(int));


        var aD_WidthParameter = aD_Width.HasValue ?
            new ObjectParameter("AD_Width", aD_Width) :
            new ObjectParameter("AD_Width", typeof(int));


        var aD_SortParameter = aD_Sort.HasValue ?
            new ObjectParameter("AD_Sort", aD_Sort) :
            new ObjectParameter("AD_Sort", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppNavigationUserGrid_Add", nAVIDParameter, aSIDParameter, aPCIDParameter, aD_WidthParameter, aD_SortParameter);
    }


    public virtual int p_tblAppNavigationUserGrid_Load(Nullable<int> nAVID, Nullable<int> aSID, string gRID, Nullable<int> filterField)
    {

        var nAVIDParameter = nAVID.HasValue ?
            new ObjectParameter("NAVID", nAVID) :
            new ObjectParameter("NAVID", typeof(int));


        var aSIDParameter = aSID.HasValue ?
            new ObjectParameter("ASID", aSID) :
            new ObjectParameter("ASID", typeof(int));


        var gRIDParameter = gRID != null ?
            new ObjectParameter("GRID", gRID) :
            new ObjectParameter("GRID", typeof(string));


        var filterFieldParameter = filterField.HasValue ?
            new ObjectParameter("FilterField", filterField) :
            new ObjectParameter("FilterField", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_tblAppNavigationUserGrid_Load", nAVIDParameter, aSIDParameter, gRIDParameter, filterFieldParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> p_tblFile_Add(string file, Nullable<System.DateTime> fL_DateCreated, Nullable<int> fTID)
    {

        var fileParameter = file != null ?
            new ObjectParameter("File", file) :
            new ObjectParameter("File", typeof(string));


        var fL_DateCreatedParameter = fL_DateCreated.HasValue ?
            new ObjectParameter("FL_DateCreated", fL_DateCreated) :
            new ObjectParameter("FL_DateCreated", typeof(System.DateTime));


        var fTIDParameter = fTID.HasValue ?
            new ObjectParameter("FTID", fTID) :
            new ObjectParameter("FTID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("p_tblFile_Add", fileParameter, fL_DateCreatedParameter, fTIDParameter);
    }

}

}

