
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppPath
{

    public int APTHID { get; set; }

    public int APPID { get; set; }

    public string APTH_Desc { get; set; }

    public string APTH_Path { get; set; }

    public Nullable<System.DateTime> APTH_Deleted { get; set; }



    public virtual tblApp tblApp { get; set; }

}

}
