
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppReportOption
{

    public int RPOID { get; set; }

    public int RPID { get; set; }

    public string RPO_Desc { get; set; }

    public Nullable<System.DateTime> RPO_Deleted { get; set; }



    public virtual tblAppReport tblAppReport { get; set; }

}

}
