
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppErrorLog
{

    public int ERID { get; set; }

    public Nullable<int> NAVID { get; set; }

    public System.DateTime ER_Date { get; set; }

    public int ER_Number { get; set; }

    public string ER_Message { get; set; }

    public short ER_Severity { get; set; }

    public short ER_State { get; set; }

    public string ER_Procedure { get; set; }

    public string ER_UserName { get; set; }

    public string ER_HostName { get; set; }



    public virtual tblAppErrorLog tblAppErrorLog1 { get; set; }

    public virtual tblAppErrorLog tblAppErrorLog2 { get; set; }

}

}
