
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppNavigation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAppNavigation()
    {

        this.tblAppColumns = new HashSet<tblAppColumns>();

        this.tblAppNavMoreButton = new HashSet<tblAppNavMoreButton>();

        this.tblAppNavigationUser = new HashSet<tblAppNavigationUser>();

    }


    public int NAVID { get; set; }

    public int BTID { get; set; }

    public string NAV_Desc { get; set; }

    public string NAV_Item { get; set; }

    public int NAV_Option { get; set; }

    public bool NAV_Filter { get; set; }

    public int NAV_Order { get; set; }

    public int NAV_Image { get; set; }

    public string NAV_Table { get; set; }

    public string NAV_Server { get; set; }

    public Nullable<System.DateTime> NAV_Deleted { get; set; }

    public bool NAV_Active { get; set; }

    public Nullable<int> NAV_GV2 { get; set; }

    public Nullable<int> NAV_GV3 { get; set; }

    public Nullable<int> NAV_GV4 { get; set; }

    public Nullable<int> NAV_GV5 { get; set; }

    public Nullable<int> NAV_GV6 { get; set; }

    public string NAV_Color { get; set; }

    public Nullable<int> NAV_Width { get; set; }

    public Nullable<int> NAV_Height { get; set; }



    public virtual tblAppButton tblAppButton { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppColumns> tblAppColumns { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppNavMoreButton> tblAppNavMoreButton { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppNavigationUser> tblAppNavigationUser { get; set; }

}

}
