
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppDropDown
{

    public int DDID { get; set; }

    public int APCID { get; set; }

    public int APPID { get; set; }

    public int NAVID { get; set; }

    public string DD_Desc { get; set; }

    public string DD_SQL { get; set; }

    public System.DateTime DD_Created { get; set; }

    public Nullable<System.DateTime> DD_Deleted { get; set; }

    public bool DD_APPID { get; set; }

    public bool DD_NAVID { get; set; }

    public bool DD_APCID { get; set; }

}

}
