
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppNavigationUserGrid
{

    public int ADID { get; set; }

    public int NAVID { get; set; }

    public int ASID { get; set; }

    public int APCID { get; set; }

    public int AD_Sort { get; set; }

    public int AD_Width { get; set; }

    public System.DateTime AD_Created { get; set; }

    public Nullable<System.DateTime> AD_Deleted { get; set; }

}

}
