
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppRoleButtons
{

    public int ABID { get; set; }

    public int ARID { get; set; }

    public int BTID { get; set; }

    public Nullable<int> AB_Order { get; set; }

    public Nullable<System.DateTime> AB_Deleted { get; set; }



    public virtual tblAppButton tblAppButton { get; set; }

    public virtual tblAppRoles tblAppRoles { get; set; }

}

}
