
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAssociate
{

    public int ASID { get; set; }

    public Nullable<int> DPID { get; set; }

    public Nullable<int> OFID { get; set; }

    public string AS_Display { get; set; }

    public string AS_First { get; set; }

    public string AS_Phone { get; set; }

    public string AS_Last { get; set; }

    public string AS_User { get; set; }

    public string AS_OutID { get; set; }

    public Nullable<System.DateTime> AS_Sync { get; set; }

    public bool AS_Active { get; set; }

    public bool AS_Reso { get; set; }

    public string AS_Email { get; set; }

    public string AS_Domain { get; set; }

    public string AS_Group { get; set; }

    public Nullable<bool> AS_DC { get; set; }

    public string AS_UserID { get; set; }

    public Nullable<int> PERNR { get; set; }

    public string Short { get; set; }

    public Nullable<int> BIDID { get; set; }

    public string AS_Badge { get; set; }

    public string AS_CellForSMS { get; set; }

    public bool AS_BI_Lock { get; set; }

    public Nullable<int> AS_CareerBand { get; set; }

    public Nullable<int> AS_CostCenter { get; set; }

    public string AS_OrgUnitAbbr { get; set; }

    public bool AS_BInonFNI { get; set; }

    public bool AS_CBandLock { get; set; }

    public string AS_HTI_Manager { get; set; }

    public Nullable<int> AS_HTI_PNum { get; set; }

    public Nullable<System.DateTime> AS_HireDate { get; set; }

}

}
