
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppButton
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAppButton()
    {

        this.tblAppNavMoreButton = new HashSet<tblAppNavMoreButton>();

        this.tblAppNavigation = new HashSet<tblAppNavigation>();

        this.tblAppRoleButtons = new HashSet<tblAppRoleButtons>();

    }


    public int BTID { get; set; }

    public int APPID { get; set; }

    public string BT_Desc { get; set; }

    public Nullable<System.DateTime> BT_Deleted { get; set; }



    public virtual tblApp tblApp { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppNavMoreButton> tblAppNavMoreButton { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppNavigation> tblAppNavigation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppRoleButtons> tblAppRoleButtons { get; set; }

}

}
