
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppUser
{

    public int AUID { get; set; }

    public int ARID { get; set; }

    public int ASID { get; set; }

    public Nullable<System.DateTime> AU_Deleted { get; set; }



    public virtual tblAppRoles tblAppRoles { get; set; }

}

}
