
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppRoles
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAppRoles()
    {

        this.tblAppRoleButtons = new HashSet<tblAppRoleButtons>();

        this.tblAppUser = new HashSet<tblAppUser>();

    }


    public int ARID { get; set; }

    public int APPID { get; set; }

    public int RLID { get; set; }

    public int AB_Level { get; set; }

    public Nullable<System.DateTime> AR_Deleted { get; set; }



    public virtual tblApp tblApp { get; set; }

    public virtual tblAppRole tblAppRole { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppRoleButtons> tblAppRoleButtons { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAppUser> tblAppUser { get; set; }

}

}
