
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppNavMoreButton
{

    public int NBID { get; set; }

    public int NAVID { get; set; }

    public int BTID { get; set; }

    public bool NB_Active { get; set; }

    public System.DateTime NB_Created { get; set; }



    public virtual tblAppButton tblAppButton { get; set; }

    public virtual tblAppNavigation tblAppNavigation { get; set; }

}

}
