
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppColumns
{

    public int APCID { get; set; }

    public int NAVID { get; set; }

    public int APCOID { get; set; }

    public string APC_Desc { get; set; }

    public string APC_Name { get; set; }

    public int APC_Width { get; set; }

    public Nullable<int> APC_Order { get; set; }

    public string APC_Grid { get; set; }

    public Nullable<bool> APC_ReadOnly { get; set; }

    public Nullable<System.DateTime> APC_Deleted { get; set; }

    public string APC_Default { get; set; }

    public string APC_QueryField { get; set; }

    public string APC_ClearValue { get; set; }

    public string APC_FilterOrder { get; set; }

    public string APC_ARIDs { get; set; }



    public virtual tblAppColumnOption tblAppColumnOption { get; set; }

    public virtual tblAppNavigation tblAppNavigation { get; set; }

}

}
