
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblDriverName
{

    public int DLNID { get; set; }

    public string DLN_Desc { get; set; }

    public bool DLN_Active { get; set; }

    public System.DateTime DLN_Created { get; set; }

    public Nullable<System.DateTime> DLN_Deleted { get; set; }

    public int DLCID { get; set; }

    public string DLN_First { get; set; }

    public string DLN_Last { get; set; }

}

}
