
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblDriverLog
{

    public int DLLID { get; set; }

    public string DLL_Desc { get; set; }

    public bool DLL_Active { get; set; }

    public System.DateTime DLL_Created { get; set; }

    public Nullable<System.DateTime> DLL_Deleted { get; set; }

    public Nullable<System.DateTime> DL_In { get; set; }

    public Nullable<System.DateTime> DL_Out { get; set; }

    public Nullable<int> DLCID { get; set; }

    public Nullable<int> DLNID { get; set; }

    public string DLL_Building { get; set; }

    public string DLL_TruckNo { get; set; }

    public Nullable<int> ASID_In { get; set; }

    public Nullable<int> ASID_Out { get; set; }

}

}
