
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmailDistributionDetail
{

    public int EDDID { get; set; }

    public int EDID { get; set; }

    public Nullable<int> ASID { get; set; }

    public string EDD_NonBoschEmail { get; set; }

    public bool EDD_Active { get; set; }

    public Nullable<System.DateTime> EDD_Deleted { get; set; }

    public System.DateTime EDD_Created { get; set; }



    public virtual tblEmailDistribution tblEmailDistribution { get; set; }

}

}
