
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmailDistribution
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblEmailDistribution()
    {

        this.tblEmailDistributionDetail = new HashSet<tblEmailDistributionDetail>();

    }


    public int EDID { get; set; }

    public string ED_Desc { get; set; }

    public string ED_SendAs { get; set; }

    public bool ED_Active { get; set; }

    public Nullable<System.DateTime> ED_Deleted { get; set; }

    public Nullable<int> APPID { get; set; }

    public System.DateTime ED_Created { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmailDistributionDetail> tblEmailDistributionDetail { get; set; }

}

}
