
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblOptions
{

    public int OPID { get; set; }

    public int OP_ID { get; set; }

    public string OP_Desc { get; set; }

    public Nullable<int> OP_Function { get; set; }

}

}
