
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblPBProxy
{

    public int XYID { get; set; }

    public int ASID { get; set; }

    public int ASID2 { get; set; }

    public System.DateTime XY_Created { get; set; }

    public Nullable<System.DateTime> XY_Deleted { get; set; }

}

}
