
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class tblShift
{

    public int SFID { get; set; }

    public string SF_Desc { get; set; }

    public bool SF_Active { get; set; }

    public System.DateTime SF_Created { get; set; }

    public Nullable<System.DateTime> SF_Deleted { get; set; }

    public Nullable<int> SF_Num { get; set; }

}

}
