
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwAppNav
{

    public int NAVID { get; set; }

    public string BT_Desc { get; set; }

    public string NAV_Desc { get; set; }

    public string NAV_Item { get; set; }

    public string NAV_Table { get; set; }

    public int NAV_Option { get; set; }

    public bool NAV_Filter { get; set; }

    public int NAV_Order { get; set; }

    public string NAV_Server { get; set; }

    public int APPID { get; set; }

    public string APP_Desc { get; set; }

}

}
