
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwAppView
{

    public int APPID { get; set; }

    public string APP_Desc { get; set; }

    public string APP_Version { get; set; }

    public string Name { get; set; }

    public string RL_Desc { get; set; }

    public int ARID { get; set; }

    public string AS_User { get; set; }

    public int ASID { get; set; }

    public int AB_Level { get; set; }

    public Nullable<int> APP_HelpdeskOrg { get; set; }

    public int AUID { get; set; }

    public int Expr1 { get; set; }

    public Nullable<System.DateTime> AU_Deleted { get; set; }

    public Nullable<System.DateTime> AR_Deleted { get; set; }

    public Nullable<System.DateTime> RL_Deleted { get; set; }

    public int RLID { get; set; }

}

}
