
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwAssociate
{

    public string FullName { get; set; }

    public string AS_First { get; set; }

    public string AS_Last { get; set; }

    public string AS_User { get; set; }

    public string AS_Email { get; set; }

    public int ARID { get; set; }

    public int AB_Level { get; set; }

    public string RL_Desc { get; set; }

    public int ASID { get; set; }

    public int AUID { get; set; }

    public int APPID { get; set; }

    public Nullable<int> PERNR { get; set; }

}

}
