
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwDriverLog
{

    public string LogEntry { get; set; }

    public Nullable<System.DateTime> TimeIn { get; set; }

    public Nullable<System.DateTime> TimeOut { get; set; }

    public string CarrierName { get; set; }

    public string DriverName { get; set; }

    public Nullable<int> DLCID { get; set; }

    public Nullable<int> DLNID { get; set; }

    public int DLLID { get; set; }

    public System.DateTime LogTimeStamp { get; set; }

    public string Building { get; set; }

    public string TruckNumber { get; set; }

    public Nullable<int> ASID_In { get; set; }

    public Nullable<int> ASID_Out { get; set; }

}

}
