
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwEmailDistribution
{

    public int EDID { get; set; }

    public string ED_Desc { get; set; }

    public string AS_Display { get; set; }

    public string AS_Email { get; set; }

    public int EDDID { get; set; }

    public string AS_CellForSMS { get; set; }

    public Nullable<int> ASID { get; set; }

}

}
