
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRLData
{

using System;
    using System.Collections.Generic;
    
public partial class vwPBTracking
{

    public string PBS_Desc { get; set; }

    public System.DateTime PBST_Date { get; set; }

    public Nullable<int> PB2ID { get; set; }

    public string PB_Material { get; set; }

    public string PB_MaterialDescription { get; set; }

    public System.DateTime PB_TrackingDate { get; set; }

    public string PB_Reason { get; set; }

    public string IssueLast { get; set; }

    public string CommentLast { get; set; }

    public string ECNNumber { get; set; }

    public int PBID { get; set; }

    public int PBDID { get; set; }

    public int PBSID { get; set; }

    public int PBPTID { get; set; }

    public int PBFTID { get; set; }

    public int PBSTID { get; set; }

    public int PBOID { get; set; }

    public int PBSFID { get; set; }

    public int PBRTID { get; set; }

    public string PB_LeadPlant { get; set; }

    public string ZMNRNumber { get; set; }

    public string ConversionNumber { get; set; }

    public string PCTNumber { get; set; }

    public Nullable<System.DateTime> PB_Deleted { get; set; }

    public int ASID { get; set; }

    public string AS_Display { get; set; }

    public System.DateTime PB_TimeStamp { get; set; }

    public string NextTask { get; set; }

    public string NextTaskOwner { get; set; }

    public string AS_Email { get; set; }

    public Nullable<System.DateTime> PBRL_Assigned { get; set; }

    public int PastDue { get; set; }

    public string ServiceRequestNumber { get; set; }

    public string FinishedUnit { get; set; }

    public int PBDVID { get; set; }

    public string PBD_Desc { get; set; }

    public string PrototypeRequestNumber { get; set; }

    public string PB_Batch { get; set; }

    public int PBXID { get; set; }

    public int PBPRID { get; set; }

    public Nullable<System.DateTime> PB_Delivery { get; set; }

    public Nullable<System.DateTime> PB_EstCompletion { get; set; }

    public string PR1_Special_Procurement { get; set; }

    public string PR1_Procurement { get; set; }

    public string PRA_Special_Procurement { get; set; }

    public string PRA_Procurement { get; set; }

    public string Organization { get; set; }

    public string Product_Type { get; set; }

    public string Lead_Plant { get; set; }

    public string Priority { get; set; }

    public string Complexity { get; set; }

    public Nullable<int> PBRL_Sort { get; set; }

    public string Customer { get; set; }

    public string ThreeDay { get; set; }

    public string Division { get; set; }

    public int PBSIDLast { get; set; }

    public Nullable<int> PBIDRed { get; set; }

}

}
