//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssociateDocShow
    {
        public int ASBID { get; set; }
        public int ASID { get; set; }
        public Nullable<System.DateTime> ASB_Deleted { get; set; }
    }
}
