//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionRole
    {
        public int CZRID { get; set; }
        public string CZR_Desc { get; set; }
        public Nullable<System.DateTime> CZR_Deleted { get; set; }
        public string CZR_DefaultTask { get; set; }
    }
}
