//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcessionRoleAssign
    {
        public int CZAID { get; set; }
        public int CZGID { get; set; }
        public int CZRID { get; set; }
        public int ASID { get; set; }
    }
}
