//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcession
    {
        public int CSSID { get; set; }
        public int CZGID { get; set; }
        public int CVID { get; set; }
        public int ASID { get; set; }
        public byte[] CSS_Image { get; set; }
        public Nullable<System.DateTime> CSS_Deleted { get; set; }
        public int ASID_Entered { get; set; }
        public string CSS_Location { get; set; }
        public bool CSS_Hot { get; set; }
        public bool CSS_Repeat { get; set; }
        public string CSS_RegNumber { get; set; }
        public System.DateTime CSS_Date { get; set; }
        public System.DateTime CSS_TimeStamp { get; set; }
        public string CSS_Supplier { get; set; }
        public string CSS_UsedIn { get; set; }
        public Nullable<System.DateTime> CSS_UseBy { get; set; }
        public string CSS_SpecialRequirement { get; set; }
        public string CSS_ActualValue { get; set; }
        public string CSS_RootCause { get; set; }
        public string CSS_Description { get; set; }
        public string CSS_AttachList { get; set; }
        public Nullable<System.DateTime> CSS_UseStart { get; set; }
    }
}
