//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocAppStatusHistory
    {
        public int DHID { get; set; }
        public int DAID { get; set; }
        public int DASID { get; set; }
        public System.DateTime DH_Created { get; set; }
    
        public virtual tblDocApproval tblDocApproval { get; set; }
        public virtual tblDocAppStatus tblDocAppStatus { get; set; }
        public virtual tblDocAppStatusHistory tblDocAppStatusHistory1 { get; set; }
        public virtual tblDocAppStatusHistory tblDocAppStatusHistory2 { get; set; }
    }
}
