//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocAppStatus
    {
        public tblDocAppStatus()
        {
            this.tblDocApproval = new HashSet<tblDocApproval>();
            this.tblDocAppStatusHistory = new HashSet<tblDocAppStatusHistory>();
        }
    
        public int DASID { get; set; }
        public string DAS_Desc { get; set; }
        public int DAS_Active { get; set; }
    
        public virtual ICollection<tblDocApproval> tblDocApproval { get; set; }
        public virtual ICollection<tblDocAppStatusHistory> tblDocAppStatusHistory { get; set; }
    }
}
