//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocLine
    {
        public tblDocLine()
        {
            this.tblDocApproval = new HashSet<tblDocApproval>();
            this.tblDocLineAsc = new HashSet<tblDocLineAsc>();
        }
    
        public int DLID { get; set; }
        public string DL_Desc { get; set; }
        public string DL_Long { get; set; }
        public Nullable<System.DateTime> DL_Deleted { get; set; }
        public bool DL_Active { get; set; }
        public Nullable<int> ASID { get; set; }
    
        public virtual ICollection<tblDocApproval> tblDocApproval { get; set; }
        public virtual ICollection<tblDocLineAsc> tblDocLineAsc { get; set; }
    }
}
