//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocAppDetail
    {
        public int DADID { get; set; }
        public int DAID { get; set; }
        public int ASID { get; set; }
        public Nullable<System.DateTime> DAD_Approved { get; set; }
        public Nullable<System.DateTime> DAD_Viewed { get; set; }
        public Nullable<int> DAD_Order { get; set; }
        public Nullable<int> DAATID { get; set; }
    
        public virtual tblDocApproval tblDocApproval { get; set; }
        public virtual tblDocApprovalType tblDocApprovalType { get; set; }
    }
}
