//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocLineAsc
    {
        public int DLDID { get; set; }
        public int DLID { get; set; }
        public int ASID { get; set; }
        public int DLD_Type { get; set; }
        public Nullable<int> DAATID { get; set; }
        public Nullable<System.DateTime> DLD_Created { get; set; }
        public Nullable<System.DateTime> DLD_Updated { get; set; }
    
        public virtual tblDocLine tblDocLine { get; set; }
    }
}
