//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocType
    {
        public tblDocType()
        {
            this.tblDoc = new HashSet<tblDoc>();
        }
    
        public int DTID { get; set; }
        public string DT_Short { get; set; }
        public string DT_Desc { get; set; }
        public int DT_Active { get; set; }
        public Nullable<System.DateTime> DT_Deleted { get; set; }
    
        public virtual ICollection<tblDoc> tblDoc { get; set; }
    }
}
