//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocApproval
    {
        public tblDocApproval()
        {
            this.tblDocAppDetail = new HashSet<tblDocAppDetail>();
            this.tblDocAppStatusHistory = new HashSet<tblDocAppStatusHistory>();
        }
    
        public int DAID { get; set; }
        public int DLID { get; set; }
        public int ASID { get; set; }
        public int DOCID { get; set; }
        public int DASID { get; set; }
        public System.DateTime DA_Date { get; set; }
        public string DA_BriefText { get; set; }
        public Nullable<int> ASID_Creator { get; set; }
        public string DA_Subtitle { get; set; }
        public string DA_Amendment { get; set; }
        public System.DateTime DA_Created { get; set; }
        public Nullable<bool> DA_Hot { get; set; }
        public Nullable<bool> DA_New { get; set; }
    
        public virtual tblDoc tblDoc { get; set; }
        public virtual ICollection<tblDocAppDetail> tblDocAppDetail { get; set; }
        public virtual tblDocApproval tblDocApproval1 { get; set; }
        public virtual tblDocApproval tblDocApproval2 { get; set; }
        public virtual tblDocAppStatus tblDocAppStatus { get; set; }
        public virtual tblDocLine tblDocLine { get; set; }
        public virtual ICollection<tblDocAppStatusHistory> tblDocAppStatusHistory { get; set; }
    }
}
