//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFile
    {
        public int FLID { get; set; }
        public string FL_Desc { get; set; }
        public System.DateTime FL_Date { get; set; }
        public Nullable<System.DateTime> FL_DateCreated { get; set; }
        public int FTID { get; set; }
        public string FL_DescArchive { get; set; }
        public Nullable<System.DateTime> FL_Completed { get; set; }
        public Nullable<int> FL_DetailCount { get; set; }
    }
}
