//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocApprovers
    {
        public int DAID { get; set; }
        public string Product { get; set; }
        public string Type { get; set; }
        public string Document { get; set; }
        public string Rev { get; set; }
        public string Title { get; set; }
        public int DOCID { get; set; }
        public int DASID { get; set; }
        public int DTID { get; set; }
        public string DA_BriefText { get; set; }
        public string DOC_URL { get; set; }
        public int DLID { get; set; }
        public Nullable<System.DateTime> DAD_Approved { get; set; }
        public Nullable<System.DateTime> DAD_Viewed { get; set; }
        public int DADID { get; set; }
        public int ASID { get; set; }
        public int DLD_Type { get; set; }
        public string AS_Email { get; set; }
        public string AS_Display { get; set; }
        public string AS_First { get; set; }
        public string AS_Last { get; set; }
        public Nullable<int> DAD_Order { get; set; }
        public string AS_User { get; set; }
        public string DAAT_Desc { get; set; }
        public Nullable<int> DAATID { get; set; }
        public string DAAT_DescLong { get; set; }
        public Nullable<int> DaysOpen { get; set; }
        public System.DateTime DA_Created { get; set; }
        public string DA_Hot { get; set; }
    }
}
