//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocApproval
    {
        public int DAID { get; set; }
        public string Product { get; set; }
        public string Type { get; set; }
        public string Document { get; set; }
        public string Rev { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public int DOCID { get; set; }
        public int DASID { get; set; }
        public int DTID { get; set; }
        public string DA_BriefText { get; set; }
        public string DOC_URL { get; set; }
        public string AS_Display { get; set; }
        public string AS_Email { get; set; }
        public int DLID { get; set; }
        public int Approved { get; set; }
        public string AS_First { get; set; }
        public Nullable<int> ASID_Creator { get; set; }
        public string Creator { get; set; }
        public string CreatorEmail { get; set; }
        public string DA_Subtitle { get; set; }
        public string DA_Amendment { get; set; }
        public Nullable<int> DaysOpen { get; set; }
        public System.DateTime DA_Created { get; set; }
        public Nullable<bool> DA_Hot { get; set; }
        public Nullable<int> ASID { get; set; }
        public string OwnerDisplay { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerFirst { get; set; }
        public string OwnerLast { get; set; }
        public Nullable<bool> DA_New { get; set; }
    }
}
