//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocAssociates
    {
        public int DAID { get; set; }
        public int ASID { get; set; }
        public string AS_Display { get; set; }
        public string AS_Email { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> Viewed { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public int DADID { get; set; }
    }
}
