namespace FPY
{
    partial class frmNavigate
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmNavigate));
            this.lstImage = new System.Windows.Forms.ImageList(this.components);
            this.imgListICO = new System.Windows.Forms.ImageList(this.components);
            this.pnlButtons = new System.Windows.Forms.Panel();
            this.lstIcons = new System.Windows.Forms.ListView();
            this.MDI = new System.Windows.Forms.MdiClient();
            this.pnlButtons.SuspendLayout();
            this.SuspendLayout();
            // 
            // lstImage
            // 
            this.lstImage.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("lstImage.ImageStream")));
            this.lstImage.TransparentColor = System.Drawing.Color.Transparent;
            this.lstImage.Images.SetKeyName(0, "ascendant5.png");
            this.lstImage.Images.SetKeyName(1, "ascendant6.png");
            this.lstImage.Images.SetKeyName(2, "bars10.png");
            this.lstImage.Images.SetKeyName(3, "bars11.png");
            this.lstImage.Images.SetKeyName(4, "bars12.png");
            this.lstImage.Images.SetKeyName(5, "bars13.png");
            this.lstImage.Images.SetKeyName(6, "bars14.png");
            this.lstImage.Images.SetKeyName(7, "bars15.png");
            this.lstImage.Images.SetKeyName(8, "bars16.png");
            this.lstImage.Images.SetKeyName(9, "bars17.png");
            this.lstImage.Images.SetKeyName(10, "bars18.png");
            this.lstImage.Images.SetKeyName(11, "bars19.png");
            this.lstImage.Images.SetKeyName(12, "bars20.png");
            this.lstImage.Images.SetKeyName(13, "bars21.png");
            this.lstImage.Images.SetKeyName(14, "bird30.png");
            this.lstImage.Images.SetKeyName(15, "black208.png");
            this.lstImage.Images.SetKeyName(16, "briefcase14.png");
            this.lstImage.Images.SetKeyName(17, "briefcase15.png");
            this.lstImage.Images.SetKeyName(18, "briefcase16.png");
            this.lstImage.Images.SetKeyName(19, "briefcase17.png");
            this.lstImage.Images.SetKeyName(20, "briefcase18.png");
            this.lstImage.Images.SetKeyName(21, "briefcase19.png");
            this.lstImage.Images.SetKeyName(22, "briefcase20.png");
            this.lstImage.Images.SetKeyName(23, "briefcase21.png");
            this.lstImage.Images.SetKeyName(24, "briefcase22.png");
            this.lstImage.Images.SetKeyName(25, "briefcase23.png");
            this.lstImage.Images.SetKeyName(26, "briefcase24.png");
            this.lstImage.Images.SetKeyName(27, "briefcase25.png");
            this.lstImage.Images.SetKeyName(28, "briefcase26.png");
            this.lstImage.Images.SetKeyName(29, "business58.png");
            this.lstImage.Images.SetKeyName(30, "business62.png");
            this.lstImage.Images.SetKeyName(31, "business63.png");
            this.lstImage.Images.SetKeyName(32, "calendar62.png");
            this.lstImage.Images.SetKeyName(33, "calendar63.png");
            this.lstImage.Images.SetKeyName(34, "calendar64.png");
            this.lstImage.Images.SetKeyName(35, "calendar65.png");
            this.lstImage.Images.SetKeyName(36, "calendar66.png");
            this.lstImage.Images.SetKeyName(37, "calendar67.png");
            this.lstImage.Images.SetKeyName(38, "calendar68.png");
            this.lstImage.Images.SetKeyName(39, "calendar69.png");
            this.lstImage.Images.SetKeyName(40, "circle54.png");
            this.lstImage.Images.SetKeyName(41, "circular85.png");
            this.lstImage.Images.SetKeyName(42, "clock43.png");
            this.lstImage.Images.SetKeyName(43, "clock44.png");
            this.lstImage.Images.SetKeyName(44, "clock45.png");
            this.lstImage.Images.SetKeyName(45, "clock46.png");
            this.lstImage.Images.SetKeyName(46, "clock47.png");
            this.lstImage.Images.SetKeyName(47, "clock48.png");
            this.lstImage.Images.SetKeyName(48, "clock49.png");
            this.lstImage.Images.SetKeyName(49, "crayon4.png");
            this.lstImage.Images.SetKeyName(50, "feather9.png");
            this.lstImage.Images.SetKeyName(51, "feather10.png");
            this.lstImage.Images.SetKeyName(52, "first21.png");
            this.lstImage.Images.SetKeyName(53, "graphic12.png");
            this.lstImage.Images.SetKeyName(54, "horizontal11.png");
            this.lstImage.Images.SetKeyName(55, "horizontal13.png");
            this.lstImage.Images.SetKeyName(56, "increasing9.png");
            this.lstImage.Images.SetKeyName(57, "ink6.png");
            this.lstImage.Images.SetKeyName(58, "line23.png");
            this.lstImage.Images.SetKeyName(59, "line24.png");
            this.lstImage.Images.SetKeyName(60, "line25.png");
            this.lstImage.Images.SetKeyName(61, "line26.png");
            this.lstImage.Images.SetKeyName(62, "line27.png");
            this.lstImage.Images.SetKeyName(63, "line28.png");
            this.lstImage.Images.SetKeyName(64, "note16.png");
            this.lstImage.Images.SetKeyName(65, "note17.png");
            this.lstImage.Images.SetKeyName(66, "note18.png");
            this.lstImage.Images.SetKeyName(67, "note19.png");
            this.lstImage.Images.SetKeyName(68, "note20.png");
            this.lstImage.Images.SetKeyName(69, "note21.png");
            this.lstImage.Images.SetKeyName(70, "note22.png");
            this.lstImage.Images.SetKeyName(71, "note23.png");
            this.lstImage.Images.SetKeyName(72, "note24.png");
            this.lstImage.Images.SetKeyName(73, "note25.png");
            this.lstImage.Images.SetKeyName(74, "notebook26.png");
            this.lstImage.Images.SetKeyName(75, "paper79.png");
            this.lstImage.Images.SetKeyName(76, "paper81.png");
            this.lstImage.Images.SetKeyName(77, "paper82.png");
            this.lstImage.Images.SetKeyName(78, "paper83.png");
            this.lstImage.Images.SetKeyName(79, "paper84.png");
            this.lstImage.Images.SetKeyName(80, "paper86.png");
            this.lstImage.Images.SetKeyName(81, "paper87.png");
            this.lstImage.Images.SetKeyName(82, "paper88.png");
            this.lstImage.Images.SetKeyName(83, "pen27.png");
            this.lstImage.Images.SetKeyName(84, "pen28.png");
            this.lstImage.Images.SetKeyName(85, "pen29.png");
            this.lstImage.Images.SetKeyName(86, "pen30.png");
            this.lstImage.Images.SetKeyName(87, "pen31.png");
            this.lstImage.Images.SetKeyName(88, "pen32.png");
            this.lstImage.Images.SetKeyName(89, "pen33.png");
            this.lstImage.Images.SetKeyName(90, "pen34.png");
            this.lstImage.Images.SetKeyName(91, "pencil39.png");
            this.lstImage.Images.SetKeyName(92, "pencil40.png");
            this.lstImage.Images.SetKeyName(93, "pencil41.png");
            this.lstImage.Images.SetKeyName(94, "pencil43.png");
            this.lstImage.Images.SetKeyName(95, "pencil44.png");
            this.lstImage.Images.SetKeyName(96, "pencil45.png");
            this.lstImage.Images.SetKeyName(97, "pie24.png");
            this.lstImage.Images.SetKeyName(98, "pie25.png");
            this.lstImage.Images.SetKeyName(99, "pie26.png");
            this.lstImage.Images.SetKeyName(100, "pie27.png");
            this.lstImage.Images.SetKeyName(101, "pie28.png");
            this.lstImage.Images.SetKeyName(102, "pie29.png");
            this.lstImage.Images.SetKeyName(103, "pie30.png");
            this.lstImage.Images.SetKeyName(104, "pie31.png");
            this.lstImage.Images.SetKeyName(105, "pie32.png");
            this.lstImage.Images.SetKeyName(106, "pyramid3.png");
            this.lstImage.Images.SetKeyName(107, "pyramid4.png");
            this.lstImage.Images.SetKeyName(108, "rising9.png");
            this.lstImage.Images.SetKeyName(109, "sand3.png");
            this.lstImage.Images.SetKeyName(110, "sand4.png");
            this.lstImage.Images.SetKeyName(111, "sand5.png");
            this.lstImage.Images.SetKeyName(112, "sand6.png");
            this.lstImage.Images.SetKeyName(113, "stopwatch4.png");
            this.lstImage.Images.SetKeyName(114, "stopwatch5.png");
            this.lstImage.Images.SetKeyName(115, "vintage51.png");
            this.lstImage.Images.SetKeyName(116, "wall17.png");
            this.lstImage.Images.SetKeyName(117, "watch10.png");
            this.lstImage.Images.SetKeyName(118, "watch11.png");
            this.lstImage.Images.SetKeyName(119, "weekly3.png");
            this.lstImage.Images.SetKeyName(120, "weekly4.png");
            this.lstImage.Images.SetKeyName(121, "wristwatch4.png");
            this.lstImage.Images.SetKeyName(122, "wristwatch5.png");
            this.lstImage.Images.SetKeyName(123, "1.png");
            this.lstImage.Images.SetKeyName(124, "1b.png");
            this.lstImage.Images.SetKeyName(125, "1c.png");
            this.lstImage.Images.SetKeyName(126, "2.png");
            this.lstImage.Images.SetKeyName(127, "2b.png");
            this.lstImage.Images.SetKeyName(128, "2c.png");
            this.lstImage.Images.SetKeyName(129, "3.png");
            this.lstImage.Images.SetKeyName(130, "3b.png");
            this.lstImage.Images.SetKeyName(131, "3c.png");
            this.lstImage.Images.SetKeyName(132, "4.png");
            this.lstImage.Images.SetKeyName(133, "4b.png");
            this.lstImage.Images.SetKeyName(134, "4d.png");
            this.lstImage.Images.SetKeyName(135, "5.png");
            this.lstImage.Images.SetKeyName(136, "5b.png");
            this.lstImage.Images.SetKeyName(137, "5c.ico");
            this.lstImage.Images.SetKeyName(138, "5c.png");
            this.lstImage.Images.SetKeyName(139, "6.png");
            this.lstImage.Images.SetKeyName(140, "6c.png");
            this.lstImage.Images.SetKeyName(141, "7.png");
            this.lstImage.Images.SetKeyName(142, "7c.png");
            this.lstImage.Images.SetKeyName(143, "8.png");
            this.lstImage.Images.SetKeyName(144, "8c.png");
            this.lstImage.Images.SetKeyName(145, "9.png");
            this.lstImage.Images.SetKeyName(146, "9d.png");
            this.lstImage.Images.SetKeyName(147, "10.png");
            this.lstImage.Images.SetKeyName(148, "10d.png");
            this.lstImage.Images.SetKeyName(149, "11.png");
            this.lstImage.Images.SetKeyName(150, "11d.png");
            this.lstImage.Images.SetKeyName(151, "12.png");
            this.lstImage.Images.SetKeyName(152, "12d.png");
            this.lstImage.Images.SetKeyName(153, "13.png");
            this.lstImage.Images.SetKeyName(154, "13d.png");
            this.lstImage.Images.SetKeyName(155, "14.png");
            this.lstImage.Images.SetKeyName(156, "14b.png");
            this.lstImage.Images.SetKeyName(157, "14d.png");
            this.lstImage.Images.SetKeyName(158, "15.png");
            this.lstImage.Images.SetKeyName(159, "15b.png");
            this.lstImage.Images.SetKeyName(160, "15d.png");
            this.lstImage.Images.SetKeyName(161, "16.png");
            this.lstImage.Images.SetKeyName(162, "16b.png");
            this.lstImage.Images.SetKeyName(163, "16d.png");
            this.lstImage.Images.SetKeyName(164, "Bank.ico");
            this.lstImage.Images.SetKeyName(165, "Briefcase.ico");
            this.lstImage.Images.SetKeyName(166, "Business People.ico");
            this.lstImage.Images.SetKeyName(167, "Business_People_01.ico");
            this.lstImage.Images.SetKeyName(168, "Calculator.ico");
            this.lstImage.Images.SetKeyName(169, "Calendar.ico");
            this.lstImage.Images.SetKeyName(170, "Calendar_01.ico");
            this.lstImage.Images.SetKeyName(171, "Card.ico");
            this.lstImage.Images.SetKeyName(172, "Catalog.ico");
            this.lstImage.Images.SetKeyName(173, "Chart.ico");
            this.lstImage.Images.SetKeyName(174, "Chart_01.gif");
            this.lstImage.Images.SetKeyName(175, "Chart_01.ico");
            this.lstImage.Images.SetKeyName(176, "Chart_02.ico");
            this.lstImage.Images.SetKeyName(177, "Chat.ico");
            this.lstImage.Images.SetKeyName(178, "Chat_01.ico");
            this.lstImage.Images.SetKeyName(179, "Close.ico");
            this.lstImage.Images.SetKeyName(180, "Configure.ico");
            this.lstImage.Images.SetKeyName(181, "Cut.ico");
            this.lstImage.Images.SetKeyName(182, "Department.ico");
            this.lstImage.Images.SetKeyName(183, "Diagram.ico");
            this.lstImage.Images.SetKeyName(184, "Download.ico");
            this.lstImage.Images.SetKeyName(185, "Fix.ico");
            this.lstImage.Images.SetKeyName(186, "Flag.ico");
            this.lstImage.Images.SetKeyName(187, "Flag_01.ico");
            this.lstImage.Images.SetKeyName(188, "Folder.ico");
            this.lstImage.Images.SetKeyName(189, "Folder_01.ico");
            this.lstImage.Images.SetKeyName(190, "Folder_share.ico");
            this.lstImage.Images.SetKeyName(191, "Help.ico");
            this.lstImage.Images.SetKeyName(192, "Home.ico");
            this.lstImage.Images.SetKeyName(193, "Home_01.ico");
            this.lstImage.Images.SetKeyName(194, "House.ico");
            this.lstImage.Images.SetKeyName(195, "increase.ico");
            this.lstImage.Images.SetKeyName(196, "Internet.ico");
            this.lstImage.Images.SetKeyName(197, "Internet_link.ico");
            this.lstImage.Images.SetKeyName(198, "Internet_link_01.ico");
            this.lstImage.Images.SetKeyName(199, "Internet_link_02.ico");
            this.lstImage.Images.SetKeyName(200, "Key.ico");
            this.lstImage.Images.SetKeyName(201, "light.ico");
            this.lstImage.Images.SetKeyName(202, "Lock.ico");
            this.lstImage.Images.SetKeyName(203, "marked_price.ico");
            this.lstImage.Images.SetKeyName(204, "office1.ico");
            this.lstImage.Images.SetKeyName(205, "office2.ico");
            this.lstImage.Images.SetKeyName(206, "office3.ico");
            this.lstImage.Images.SetKeyName(207, "office4.ico");
            this.lstImage.Images.SetKeyName(208, "office5.ico");
            this.lstImage.Images.SetKeyName(209, "options.ico");
            this.lstImage.Images.SetKeyName(210, "People.ico");
            this.lstImage.Images.SetKeyName(211, "Refresh.ico");
            this.lstImage.Images.SetKeyName(212, "Shopping.ico");
            this.lstImage.Images.SetKeyName(213, "Tool.ico");
            this.lstImage.Images.SetKeyName(214, "Trash.ico");
            this.lstImage.Images.SetKeyName(215, "Unlocked.ico");
            this.lstImage.Images.SetKeyName(216, "User Card.ico");
            this.lstImage.Images.SetKeyName(217, "User_info.ico");
            this.lstImage.Images.SetKeyName(218, "Usercard_01.ico");
            this.lstImage.Images.SetKeyName(219, "Usercard_Beta.ico");
            this.lstImage.Images.SetKeyName(220, "Users_Group.ico");
            this.lstImage.Images.SetKeyName(221, "Zoom in.ico");
            this.lstImage.Images.SetKeyName(222, "Zoom out.ico");
            this.lstImage.Images.SetKeyName(223, "aaaBetaStar.ico");
            this.lstImage.Images.SetKeyName(224, "accept.ico");
            this.lstImage.Images.SetKeyName(225, "add.ico");
            this.lstImage.Images.SetKeyName(226, "addfile.ico");
            this.lstImage.Images.SetKeyName(227, "adduser.ico");
            this.lstImage.Images.SetKeyName(228, "app.ico");
            this.lstImage.Images.SetKeyName(229, "back.ico");
            this.lstImage.Images.SetKeyName(230, "backward.ico");
            this.lstImage.Images.SetKeyName(231, "bug.ico");
            this.lstImage.Images.SetKeyName(232, "burn.ico");
            this.lstImage.Images.SetKeyName(233, "cd.ico");
            this.lstImage.Images.SetKeyName(234, "chat.ico");
            this.lstImage.Images.SetKeyName(235, "chat_beta.ico");
            this.lstImage.Images.SetKeyName(236, "clock.ico");
            this.lstImage.Images.SetKeyName(237, "close.ico");
            this.lstImage.Images.SetKeyName(238, "configure.ico");
            this.lstImage.Images.SetKeyName(239, "console.ico");
            this.lstImage.Images.SetKeyName(240, "consoleBeta.ico");
            this.lstImage.Images.SetKeyName(241, "cut.ico");
            this.lstImage.Images.SetKeyName(242, "cutb.ico");
            this.lstImage.Images.SetKeyName(243, "database.ico");
            this.lstImage.Images.SetKeyName(244, "delete.ico");
            this.lstImage.Images.SetKeyName(245, "deletefile.ico");
            this.lstImage.Images.SetKeyName(246, "deleteuser.ico");
            this.lstImage.Images.SetKeyName(247, "documentsorcopy.ico");
            this.lstImage.Images.SetKeyName(248, "down.ico");
            this.lstImage.Images.SetKeyName(249, "edit.ico");
            this.lstImage.Images.SetKeyName(250, "fav.ico");
            this.lstImage.Images.SetKeyName(251, "favadd.ico");
            this.lstImage.Images.SetKeyName(252, "favb.ico");
            this.lstImage.Images.SetKeyName(253, "favbadd.ico");
            this.lstImage.Images.SetKeyName(254, "file.ico");
            this.lstImage.Images.SetKeyName(255, "filelocked.ico");
            this.lstImage.Images.SetKeyName(256, "filesearch.ico");
            this.lstImage.Images.SetKeyName(257, "find.ico");
            this.lstImage.Images.SetKeyName(258, "floppy.ico");
            this.lstImage.Images.SetKeyName(259, "folder.ico");
            this.lstImage.Images.SetKeyName(260, "folderlocked.ico");
            this.lstImage.Images.SetKeyName(261, "foldermove.ico");
            this.lstImage.Images.SetKeyName(262, "folderopen.ico");
            this.lstImage.Images.SetKeyName(263, "foldersearch.ico");
            this.lstImage.Images.SetKeyName(264, "forward.ico");
            this.lstImage.Images.SetKeyName(265, "gotoapp.ico");
            this.lstImage.Images.SetKeyName(266, "gowebsite.ico");
            this.lstImage.Images.SetKeyName(267, "groupofusers.ico");
            this.lstImage.Images.SetKeyName(268, "hd.ico");
            this.lstImage.Images.SetKeyName(269, "hdlocked.ico");
            this.lstImage.Images.SetKeyName(270, "hdsearch.ico");
            this.lstImage.Images.SetKeyName(271, "help.ico");
            this.lstImage.Images.SetKeyName(272, "home.ico");
            this.lstImage.Images.SetKeyName(273, "infoabout.ico");
            this.lstImage.Images.SetKeyName(274, "key.ico");
            this.lstImage.Images.SetKeyName(275, "lock.ico");
            this.lstImage.Images.SetKeyName(276, "mail.ico");
            this.lstImage.Images.SetKeyName(277, "mailpgp.ico");
            this.lstImage.Images.SetKeyName(278, "mailsend.ico");
            this.lstImage.Images.SetKeyName(279, "money.ico");
            this.lstImage.Images.SetKeyName(280, "moneyb.ico");
            this.lstImage.Images.SetKeyName(281, "moneyc.ico");
            this.lstImage.Images.SetKeyName(282, "movefile.ico");
            this.lstImage.Images.SetKeyName(283, "music.ico");
            this.lstImage.Images.SetKeyName(284, "network.ico");
            this.lstImage.Images.SetKeyName(285, "networkoptions.ico");
            this.lstImage.Images.SetKeyName(286, "networksearch.ico");
            this.lstImage.Images.SetKeyName(287, "next.ico");
            this.lstImage.Images.SetKeyName(288, "paint.ico");
            this.lstImage.Images.SetKeyName(289, "pastfile.ico");
            this.lstImage.Images.SetKeyName(290, "pause.ico");
            this.lstImage.Images.SetKeyName(291, "pictures.ico");
            this.lstImage.Images.SetKeyName(292, "play.ico");
            this.lstImage.Images.SetKeyName(293, "printer.ico");
            this.lstImage.Images.SetKeyName(294, "printpreview.ico");
            this.lstImage.Images.SetKeyName(295, "redo.ico");
            this.lstImage.Images.SetKeyName(296, "refresh.gif");
            this.lstImage.Images.SetKeyName(297, "refresh.ico");
            this.lstImage.Images.SetKeyName(298, "saveas.ico");
            this.lstImage.Images.SetKeyName(299, "stats.ico");
            this.lstImage.Images.SetKeyName(300, "stop.ico");
            this.lstImage.Images.SetKeyName(301, "textfile.ico");
            this.lstImage.Images.SetKeyName(302, "trash.ico");
            this.lstImage.Images.SetKeyName(303, "trashb.ico");
            this.lstImage.Images.SetKeyName(304, "undo.ico");
            this.lstImage.Images.SetKeyName(305, "up.ico");
            this.lstImage.Images.SetKeyName(306, "user.ico");
            this.lstImage.Images.SetKeyName(307, "userb.ico");
            this.lstImage.Images.SetKeyName(308, "userid.ico");
            this.lstImage.Images.SetKeyName(309, "userlock.ico");
            this.lstImage.Images.SetKeyName(310, "web.ico");
            this.lstImage.Images.SetKeyName(311, "webhd.ico");
            this.lstImage.Images.SetKeyName(312, "weblocked.ico");
            this.lstImage.Images.SetKeyName(313, "weboptions.ico");
            this.lstImage.Images.SetKeyName(314, "websearch.ico");
            this.lstImage.Images.SetKeyName(315, "window.ico");
            this.lstImage.Images.SetKeyName(316, "windowb.ico");
            this.lstImage.Images.SetKeyName(317, "wizard.ico");
            this.lstImage.Images.SetKeyName(318, "zoomin.ico");
            this.lstImage.Images.SetKeyName(319, "zoomout.ico");
            this.lstImage.Images.SetKeyName(320, "Credo.ico");
            this.lstImage.Images.SetKeyName(321, "barscode.png");
            this.lstImage.Images.SetKeyName(322, "business64.png");
            this.lstImage.Images.SetKeyName(323, "chat103.png");
            this.lstImage.Images.SetKeyName(324, "coffee128.png");
            this.lstImage.Images.SetKeyName(325, "download175.png");
            this.lstImage.Images.SetKeyName(326, "edition5.png");
            this.lstImage.Images.SetKeyName(327, "football161.png");
            this.lstImage.Images.SetKeyName(328, "fullscreen3.png");
            this.lstImage.Images.SetKeyName(329, "inspiration.png");
            this.lstImage.Images.SetKeyName(330, "lightning31.png");
            this.lstImage.Images.SetKeyName(331, "loudspeaker17.png");
            this.lstImage.Images.SetKeyName(332, "manager3.png");
            this.lstImage.Images.SetKeyName(333, "marketing8.png");
            this.lstImage.Images.SetKeyName(334, "mind.png");
            this.lstImage.Images.SetKeyName(335, "office-worker2.png");
            this.lstImage.Images.SetKeyName(336, "pin56.png");
            this.lstImage.Images.SetKeyName(337, "target50.png");
            this.lstImage.Images.SetKeyName(338, "traffic29.png");
            this.lstImage.Images.SetKeyName(339, "woman132.png");
            this.lstImage.Images.SetKeyName(340, "airconditioner.png");
            this.lstImage.Images.SetKeyName(341, "car17.png");
            this.lstImage.Images.SetKeyName(342, "cog3.png");
            this.lstImage.Images.SetKeyName(343, "cogwheel43.png");
            this.lstImage.Images.SetKeyName(344, "constructor4.png");
            this.lstImage.Images.SetKeyName(345, "data26.png");
            this.lstImage.Images.SetKeyName(346, "delivery27.png");
            this.lstImage.Images.SetKeyName(347, "electricity3.png");
            this.lstImage.Images.SetKeyName(348, "game93.png");
            this.lstImage.Images.SetKeyName(349, "gear74.png");
            this.lstImage.Images.SetKeyName(350, "gears6.png");
            this.lstImage.Images.SetKeyName(351, "glasses2.png");
            this.lstImage.Images.SetKeyName(352, "laptop65.png");
            this.lstImage.Images.SetKeyName(353, "light-bulb10.png");
            this.lstImage.Images.SetKeyName(354, "man63.png");
            this.lstImage.Images.SetKeyName(355, "man298.png");
            this.lstImage.Images.SetKeyName(356, "marriage1.png");
            this.lstImage.Images.SetKeyName(357, "maths28.png");
            this.lstImage.Images.SetKeyName(358, "mouse19.png");
            this.lstImage.Images.SetKeyName(359, "photo137.png");
            this.lstImage.Images.SetKeyName(360, "physics5.png");
            this.lstImage.Images.SetKeyName(361, "settings7.png");
            this.lstImage.Images.SetKeyName(362, "spa16.png");
            this.lstImage.Images.SetKeyName(363, "vehicle40.png");
            this.lstImage.Images.SetKeyName(364, "wrenches12.png");
            this.lstImage.Images.SetKeyName(365, "add-user.png");
            this.lstImage.Images.SetKeyName(366, "agenda.png");
            this.lstImage.Images.SetKeyName(367, "alarm-clock.png");
            this.lstImage.Images.SetKeyName(368, "avatar.png");
            this.lstImage.Images.SetKeyName(369, "avatar-1.png");
            this.lstImage.Images.SetKeyName(370, "bar-chart.png");
            this.lstImage.Images.SetKeyName(371, "bluetooth.png");
            this.lstImage.Images.SetKeyName(372, "book.png");
            this.lstImage.Images.SetKeyName(373, "box.png");
            this.lstImage.Images.SetKeyName(374, "calculator.png");
            this.lstImage.Images.SetKeyName(375, "car.png");
            this.lstImage.Images.SetKeyName(376, "charging.png");
            this.lstImage.Images.SetKeyName(377, "cloud.png");
            this.lstImage.Images.SetKeyName(378, "computing-cloud.png");
            this.lstImage.Images.SetKeyName(379, "computing-cloud-1.png");
            this.lstImage.Images.SetKeyName(380, "connections.png");
            this.lstImage.Images.SetKeyName(381, "credit-card.png");
            this.lstImage.Images.SetKeyName(382, "cursor.png");
            this.lstImage.Images.SetKeyName(383, "cutlery.png");
            this.lstImage.Images.SetKeyName(384, "documents.png");
            this.lstImage.Images.SetKeyName(385, "download.png");
            this.lstImage.Images.SetKeyName(386, "edit.png");
            this.lstImage.Images.SetKeyName(387, "envelope.png");
            this.lstImage.Images.SetKeyName(388, "eraser.png");
            this.lstImage.Images.SetKeyName(389, "error.png");
            this.lstImage.Images.SetKeyName(390, "explore.png");
            this.lstImage.Images.SetKeyName(391, "eye.png");
            this.lstImage.Images.SetKeyName(392, "fast-forward.png");
            this.lstImage.Images.SetKeyName(393, "favorite.png");
            this.lstImage.Images.SetKeyName(394, "filter.png");
            this.lstImage.Images.SetKeyName(395, "flag.png");
            this.lstImage.Images.SetKeyName(396, "folder.png");
            this.lstImage.Images.SetKeyName(397, "folder-1.png");
            this.lstImage.Images.SetKeyName(398, "full-battery.png");
            this.lstImage.Images.SetKeyName(399, "gamepad.png");
            this.lstImage.Images.SetKeyName(400, "garbage.png");
            this.lstImage.Images.SetKeyName(401, "heart.png");
            this.lstImage.Images.SetKeyName(402, "home.png");
            this.lstImage.Images.SetKeyName(403, "information.png");
            this.lstImage.Images.SetKeyName(404, "insight.png");
            this.lstImage.Images.SetKeyName(405, "interface.png");
            this.lstImage.Images.SetKeyName(406, "laptop.png");
            this.lstImage.Images.SetKeyName(407, "layers.png");
            this.lstImage.Images.SetKeyName(408, "light-bulb.png");
            this.lstImage.Images.SetKeyName(409, "like.png");
            this.lstImage.Images.SetKeyName(410, "location.png");
            this.lstImage.Images.SetKeyName(411, "loudspeaker.png");
            this.lstImage.Images.SetKeyName(412, "mail.png");
            this.lstImage.Images.SetKeyName(413, "mail-1.png");
            this.lstImage.Images.SetKeyName(414, "mail-2.png");
            this.lstImage.Images.SetKeyName(415, "map.png");
            this.lstImage.Images.SetKeyName(416, "medal.png");
            this.lstImage.Images.SetKeyName(417, "message.png");
            this.lstImage.Images.SetKeyName(418, "microphone.png");
            this.lstImage.Images.SetKeyName(419, "money.png");
            this.lstImage.Images.SetKeyName(420, "monitor.png");
            this.lstImage.Images.SetKeyName(421, "musical-note.png");
            this.lstImage.Images.SetKeyName(422, "next.png");
            this.lstImage.Images.SetKeyName(423, "next-1.png");
            this.lstImage.Images.SetKeyName(424, "notification.png");
            this.lstImage.Images.SetKeyName(425, "padlock.png");
            this.lstImage.Images.SetKeyName(426, "page.png");
            this.lstImage.Images.SetKeyName(427, "paint.png");
            this.lstImage.Images.SetKeyName(428, "paper.png");
            this.lstImage.Images.SetKeyName(429, "pause.png");
            this.lstImage.Images.SetKeyName(430, "photo-camera.png");
            this.lstImage.Images.SetKeyName(431, "picture.png");
            this.lstImage.Images.SetKeyName(432, "planet-earth.png");
            this.lstImage.Images.SetKeyName(433, "play-button.png");
            this.lstImage.Images.SetKeyName(434, "playlist.png");
            this.lstImage.Images.SetKeyName(435, "presentation.png");
            this.lstImage.Images.SetKeyName(436, "printer.png");
            this.lstImage.Images.SetKeyName(437, "record.png");
            this.lstImage.Images.SetKeyName(438, "reload.png");
            this.lstImage.Images.SetKeyName(439, "remove-user.png");
            this.lstImage.Images.SetKeyName(440, "rss-feed.png");
            this.lstImage.Images.SetKeyName(441, "safebox.png");
            this.lstImage.Images.SetKeyName(442, "safety.png");
            this.lstImage.Images.SetKeyName(443, "science.png");
            this.lstImage.Images.SetKeyName(444, "search.png");
            this.lstImage.Images.SetKeyName(445, "settings.png");
            this.lstImage.Images.SetKeyName(446, "settings-1.png");
            this.lstImage.Images.SetKeyName(447, "share.png");
            this.lstImage.Images.SetKeyName(448, "shield.png");
            this.lstImage.Images.SetKeyName(449, "shopping-cart.png");
            this.lstImage.Images.SetKeyName(450, "smartphone.png");
            this.lstImage.Images.SetKeyName(451, "speaker.png");
            this.lstImage.Images.SetKeyName(452, "speaker-1.png");
            this.lstImage.Images.SetKeyName(453, "speech-balloon.png");
            this.lstImage.Images.SetKeyName(454, "speech-bubble.png");
            this.lstImage.Images.SetKeyName(455, "telephone.png");
            this.lstImage.Images.SetKeyName(456, "tick.png");
            this.lstImage.Images.SetKeyName(457, "trophy.png");
            this.lstImage.Images.SetKeyName(458, "unlocked.png");
            this.lstImage.Images.SetKeyName(459, "upload.png");
            this.lstImage.Images.SetKeyName(460, "user-list.png");
            this.lstImage.Images.SetKeyName(461, "video-camera.png");
            this.lstImage.Images.SetKeyName(462, "wifi.png");
            this.lstImage.Images.SetKeyName(463, "zoom.png");
            this.lstImage.Images.SetKeyName(464, "zoom-out.png");
            this.lstImage.Images.SetKeyName(465, "brightIdeas.ico");
            this.lstImage.Images.SetKeyName(466, "bulb.ico");
            this.lstImage.Images.SetKeyName(467, "Inspect.ico");
            this.lstImage.Images.SetKeyName(468, "AddDocRed.ico");
            this.lstImage.Images.SetKeyName(469, "AddIDRed.ico");
            this.lstImage.Images.SetKeyName(470, "BoxShippingRed.ico");
            this.lstImage.Images.SetKeyName(471, "ClipboardListRed.ico");
            this.lstImage.Images.SetKeyName(472, "ColumnsRed.ico");
            this.lstImage.Images.SetKeyName(473, "InspectRed.ico");
            this.lstImage.Images.SetKeyName(474, "Scan1Red.ico");
            this.lstImage.Images.SetKeyName(475, "Scan2Red.ico");
            this.lstImage.Images.SetKeyName(476, "Scan3Red.ico");
            this.lstImage.Images.SetKeyName(477, "ScannerRed.ico");
            this.lstImage.Images.SetKeyName(478, "ShippingRed.ico");
            this.lstImage.Images.SetKeyName(479, "PackBoxRed.ico");
            this.lstImage.Images.SetKeyName(480, "CompScreen.ico");
            this.lstImage.Images.SetKeyName(481, "noun_Water Pump_1083061_1e18a8.png");
            this.lstImage.Images.SetKeyName(482, "noun_preferences_1082948_1e18a8.png");
            this.lstImage.Images.SetKeyName(483, "noun_electron_1082943_1e18a8.png");
            this.lstImage.Images.SetKeyName(484, "noun_Crane_1082923_1e18a8.png");
            this.lstImage.Images.SetKeyName(485, "noun_tool kit_1082915_1e18a8.png");
            this.lstImage.Images.SetKeyName(486, "noun_Document_1082917_1e18a8.png");
            this.lstImage.Images.SetKeyName(487, "noun_cog_1082897_1e18a8.png");
            this.lstImage.Images.SetKeyName(488, "noun_tools_1082895_1e18a8.png");
            this.lstImage.Images.SetKeyName(489, "noun_Light Bulb_1082890_1e18a8.png");
            this.lstImage.Images.SetKeyName(490, "noun_atom_1082889_1e18a8.png");
            this.lstImage.Images.SetKeyName(491, "noun_Web Conversion Funnel_1837727_070246.png");
            this.lstImage.Images.SetKeyName(492, "noun_Cyber Eye_1837709_070246 (1).png");
            this.lstImage.Images.SetKeyName(493, "noun_Cyber Eye_1837709_070246.png");
            this.lstImage.Images.SetKeyName(494, "noun_global network_1837702_070246.png");
            this.lstImage.Images.SetKeyName(495, "noun_shared web hosting_1837693_070246.png");
            this.lstImage.Images.SetKeyName(496, "noun_Network Structure_1837687_070246.png");
            this.lstImage.Images.SetKeyName(497, "noun_computer graphics_1837679_070246.png");
            this.lstImage.Images.SetKeyName(498, "noun_Mobile Search_1837677_070246.png");
            this.lstImage.Images.SetKeyName(499, "noun_global network_1837675_070246.png");
            this.lstImage.Images.SetKeyName(500, "noun_file sharing_1837671_070246.png");
            this.lstImage.Images.SetKeyName(501, "noun_Cyber Eye_1837670_070246.png");
            this.lstImage.Images.SetKeyName(502, "noun_technical support_1837669_070246.png");
            this.lstImage.Images.SetKeyName(503, "noun_Network topology_1837666_070246.png");
            this.lstImage.Images.SetKeyName(504, "noun_Talking man_1837665_070246.png");
            this.lstImage.Images.SetKeyName(505, "noun_shared web hosting_1837664_070246.png");
            this.lstImage.Images.SetKeyName(506, "noun_server network_1837661_070246.png");
            this.lstImage.Images.SetKeyName(507, "noun_Gear_1837660_070246.png");
            this.lstImage.Images.SetKeyName(508, "noun_Domain Name Registration_1837736_070246.png");
            this.lstImage.Images.SetKeyName(509, "noun_Data Organization_1837657_070246.png");
            this.lstImage.Images.SetKeyName(510, "noun_Cloud Network_1837737_070246.png");
            this.lstImage.Images.SetKeyName(511, "noun_Statistical analysis_1837718_070246.png");
            this.lstImage.Images.SetKeyName(512, "noun_Mobile Search_1837677_070246 (1).png");
            this.lstImage.Images.SetKeyName(513, "noun_gear magnifier_1837707_070246.png");
            this.lstImage.Images.SetKeyName(514, "noun_clock_1571590_191970.png");
            this.lstImage.Images.SetKeyName(515, "noun_Give Analytics_1097874_191970.png");
            this.lstImage.Images.SetKeyName(516, "noun_home monitor dashboard_1849856_191970.png");
            this.lstImage.Images.SetKeyName(517, "noun_save time_1854483_191970.png");
            this.lstImage.Images.SetKeyName(518, "noun_Target_1854591_191970.png");
            this.lstImage.Images.SetKeyName(519, "noun_Timed task management_1854577.ico");
            this.lstImage.Images.SetKeyName(520, "noun_Timed Web Task Management_1854478.ico");
            this.lstImage.Images.SetKeyName(521, "noun_Online Speeds_1615547_191970.png");
            this.lstImage.Images.SetKeyName(522, "noun_Archery_287470.ico");
            this.lstImage.Images.SetKeyName(523, "noun_bar chart_1614897.ico");
            this.lstImage.Images.SetKeyName(524, "noun_scatter graph_1614838.ico");
            this.lstImage.Images.SetKeyName(525, "noun_scatter graph_1614904.ico");
            this.lstImage.Images.SetKeyName(526, "noun_Target_1854591_191970.png");
            this.lstImage.Images.SetKeyName(527, "noun_Online Speeds_1615547_191970.png");
            this.lstImage.Images.SetKeyName(528, "noun_Data Analysis_1718370_191970.png");
            this.lstImage.Images.SetKeyName(529, "noun_columns_210426.ico");
            this.lstImage.Images.SetKeyName(530, "noun_Calendar_707383_191970.png");
            this.lstImage.Images.SetKeyName(531, "noun_control panel_3371672.ico");
            this.lstImage.Images.SetKeyName(532, "noun_Technical Maintenance_1848908_191970.png");
            this.lstImage.Images.SetKeyName(533, "noun_columns_210426.png");
            // 
            // imgListICO
            // 
            this.imgListICO.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imgListICO.ImageStream")));
            this.imgListICO.TransparentColor = System.Drawing.Color.Transparent;
            this.imgListICO.Images.SetKeyName(0, "oie_transparent.ico");
            this.imgListICO.Images.SetKeyName(1, "bulb.ico");
            // 
            // pnlButtons
            // 
            this.pnlButtons.Controls.Add(this.lstIcons);
            this.pnlButtons.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlButtons.Location = new System.Drawing.Point(0, 0);
            this.pnlButtons.Name = "pnlButtons";
            this.pnlButtons.Size = new System.Drawing.Size(128, 395);
            this.pnlButtons.TabIndex = 1;
            this.pnlButtons.Visible = false;
            // 
            // lstIcons
            // 
            this.lstIcons.BackColor = System.Drawing.Color.White;
            this.lstIcons.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstIcons.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstIcons.LargeImageList = this.lstImage;
            this.lstIcons.Location = new System.Drawing.Point(0, 0);
            this.lstIcons.MultiSelect = false;
            this.lstIcons.Name = "lstIcons";
            this.lstIcons.Size = new System.Drawing.Size(128, 395);
            this.lstIcons.TabIndex = 0;
            this.lstIcons.Tag = "0";
            this.lstIcons.UseCompatibleStateImageBehavior = false;
            this.lstIcons.MouseLeave += new System.EventHandler(this.lstIcons_MouseLeave);
            this.lstIcons.MouseMove += new System.Windows.Forms.MouseEventHandler(this.lstIcons_MouseMove);
            this.lstIcons.MouseUp += new System.Windows.Forms.MouseEventHandler(this.lstIcons_MouseUp);
            // 
            // MDI
            // 
            this.MDI.BackColor = System.Drawing.Color.Ivory;
            this.MDI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MDI.Location = new System.Drawing.Point(128, 0);
            this.MDI.Name = "MDI";
            this.MDI.Size = new System.Drawing.Size(668, 395);
            this.MDI.TabIndex = 2;
            // 
            // frmNavigate
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Beige;
            this.ClientSize = new System.Drawing.Size(796, 395);
            this.Controls.Add(this.pnlButtons);
            this.Controls.Add(this.MDI);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.Name = "frmNavigate";
            this.Text = "frmNavigate";
            this.Load += new System.EventHandler(this.frmNavigate_Load);
            this.Shown += new System.EventHandler(this.frmNavigate_Shown);
            this.SizeChanged += new System.EventHandler(this.frmNavigate_SizeChanged);
            this.pnlButtons.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlButtons;
        private System.Windows.Forms.ListView lstIcons;
        private System.Windows.Forms.MdiClient MDI;
        public System.Windows.Forms.ImageList lstImage;
        private System.Windows.Forms.ImageList imgListICO;
    }
}